const test=require('node:test'),assert=require('node:assert/strict');
const D=require('./data'),P=require('./progression'),W=require('./world'),L=require('./level-up'),Save=require('./run-save');
function fight(run,enc,seed,magicFirst=false){const b=P.battleFor(run,enc,W.seeded(seed));for(let i=0;i<3600&&b.phase==='fighting';i++){if(!b.player.cast)for(const id of magicFirst?['nova','fire','quick']:['nova','quick','fire'])if(b.choose(id).ok)break;b.advance(.05);}P.carryBattleCharge(run,b);if(run.dungeon&&b.phase==='victory')run.dungeonResources={hp:b.player.hp,mana:b.player.mana,stamina:b.player.stamina};return b.phase==='victory';}
function mine(level,seed){const run=P.createRun(P.freshProgress());run.level=level;run.dungeon={id:'abandoned_mine',stage:0};for(let i=0;i<4;i++){run.dungeon.stage=i;const e=P.dungeonEncounter(run);if(!fight(run,e,seed+i,seed%2))return false;P.grantExp(run,e.level,e.type);}return true;}
test('新收藏只有物理魔法各一招、無被動技能，初始裝備不含高階武器',()=>{const p=P.freshProgress(),r=P.createRun(p);assert.deepEqual(p.moves,{quick:1,fire:1});assert.deepEqual(p.skills,[]);assert.deepEqual(r.build.talents,[]);assert.equal(r.build.moves.length,2);assert.equal(p.equipment.includes('greatsword'),false);assert.deepEqual(P.statsFor(r),{hp:150,stamina:59,mana:40,agility:25,luck:5});});
test('100 組亂數：初始能打附近小怪、無法直接通關礦坑；成長後可通關',()=>{let beginner=0,initialClear=0,grownClear=0;for(let seed=1;seed<=100;seed++){if(fight(P.createRun(P.freshProgress()),{type:'greywind_0',level:2},seed))beginner++;if(mine(1,seed))initialClear++;if(mine(15,seed))grownClear++;}assert.ok(beginner>=90);assert.equal(initialClear,0);assert.ok(grownClear>=60);});
test('一口氣升多級的五項增幅等於實際能力差，無配點與重複發放',()=>{const r=P.createRun(P.freshProgress());const before=P.statsFor(r);r.exp=P.levelCost(1)+P.levelCost(2)+P.levelCost(3);const exp=P.grantExp(r,1);assert.ok(exp.levels>=3);assert.equal(r.points,0);for(const k of Object.keys(before)){assert.equal(exp.beforeStats[k],before[k]);assert.equal(exp.afterStats[k],P.statsFor(r)[k]);assert.ok(exp.afterStats[k]>before[k]);}const stats=JSON.stringify(P.statsFor(r));L.html(exp);L.value(1,r.level,3);assert.equal(JSON.stringify(P.statsFor(r)),stats);assert.equal(P.allocate(r,'hp'),false);});
test('數字動畫單調增加且停在實際值；減少動態直接顯示結果',()=>{for(const [from,to]of [[150,186],[25,28.6],[1,4]]){let last=from;for(let t=0;t<3;t+=.05){const n=L.value(from,to,t,.3);assert.ok(n>=last&&n<=to);last=n;}assert.equal(L.value(from,to,3,.3),to);assert.equal(L.value(from,to,0,.3,true),to);}});
test('原有收藏與配好的技能保留；舊存檔剩餘配點不再發放',()=>{const p=P.freshProgress();p.moves.heavy=3;p.skills=['vigor'];const loaded=P.loadProgress({getItem:()=>JSON.stringify(p)}).progress;assert.equal(loaded.moves.heavy,3);assert.deepEqual(loaded.skills,['vigor']);const run=P.createRun(loaded);run.points=5;run.allocated.hp=2;const g={scene:'explore',run,permanent:loaded,build:run.build},s={raw:null,setItem(k,v){this.raw=v;},getItem(){return this.raw;}};Save.save(s,g);const snapshot=Save.load(s).snapshot;assert.equal(snapshot.run.points,0);assert.equal(snapshot.run.allocated.hp,2);assert.equal(snapshot.permanent.moves.heavy,3);});
test('原本免費提供的技能與普通招式仍可從正式探索池取得',()=>{const skills=new Set(),moves=new Set();for(const p of Object.values(D.rewardPools))for(const e of p.entries){if(e.rewardType==='talents')e.rewardIds.forEach(id=>skills.add(id));if(e.rewardType==='moves')e.rewardIds.forEach(id=>moves.add(id));}for(const id of ['vigor','control','agility','lucky','vitality','endurance','mana_boost','swift','fortunate'])assert.ok(skills.has(id));for(const id of ['quick','fire','heavy','interrupt'])assert.ok(moves.has(id));});
