const test=require('node:test'),assert=require('node:assert/strict'),P=require('./progression'),D=require('./data'),C=require('./engine'),R=require('./skill-runtime'),J=require('./build-journey'),Save=require('./run-save');
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function battle(gear={},talents=[]){const p=P.freshProgress();p.equipment=Object.keys(D.equipment);p.moves=Object.fromEntries(Object.keys(D.moves).map(id=>[id,1]));p.skills=Object.keys(D.skills);const build={...P.defaultBuild(),moves:['double_slash','lesser_heal','interrupt','quick'],talents,equipment:{...P.defaultBuild().equipment,...gear}},r=P.createRun(p,build),b=P.battleFor(r,{type:'greywind_0',level:10},()=>.99);b.enemy.hp=b.enemy.stats.hp=100000;b.enemy.cast=null;return {p,r,b};}
test('三件特殊裝備品級、唯一主題地下城、稀有池可取得',()=>{for(const [id,source]of [['mercy_mantle','sunken_temple'],['echo_bracers','giant_ruins'],['breaker_boots','frozen_tower']]){const e=D.equipment[id];assert.equal(e.powerGrade,'A');assert.deepEqual(e.sourceDungeons,[source]);const d=D.dungeons.find(d=>d.id===source);assert.ok(D.rewardPools[d.rareRewardPool].entries.some(x=>x.rewardIds.includes(id)));}});
test('溢出治療轉盾有上限，不計戰後補滿與被動回復，吸收記實際值',()=>{const {b}=battle({chest:'mercy_mantle'});b.player.hp=b.player.stats.hp-10;const heal={move:D.moves.lesser_heal};b.recover(b.player,'hp',30,heal);near(b.player.shield,10);near(b.buildReport.healing,10);b.recover(b.player,'hp',1000,heal);near(b.player.shield,b.player.stats.hp*.12);const shield=b.player.shield;b.receiveDamage(b.enemy,b.player,shield+5,D.moves.slime);near(b.buildReport.shieldAbsorbed,shield);b.recover(b.player,'hp',100,{...heal,sourceId:'passive'});near(b.player.shield,0);b.restore();near(b.player.shield,0);assert.ok(b.buildReport.sources.mercy_mantle.shieldCreated>0);});
test('末擊追響只追加一次、與殘影獨立，總傷害與實扣HP一致',()=>{const {b}=battle({arms:'echo_bracers'},['afterimage']);const hp=b.enemy.hp;b.choose('double_slash');b.resolve(b.player);while(b.player.sequence)b.resolveSequenceHit(b.player);assert.equal(b.delayedHits.filter(x=>x.sourceId==='echo_bracers').length,1);assert.ok(b.delayedHits.some(x=>x.sourceId==='afterimage'));while(b.delayedHits.length)b.resolveDelayedHit();near(b.buildReport.damage,hp-b.enemy.hp);assert.ok(b.buildReport.sources.echo_bracers.damage>0);assert.ok(b.buildReport.sources.afterimage.damage>0);const count=b.delayedHits.length;assert.equal(count,0);});
test('斷詠戰靴只在成功中斷恢復SP，霸體防止中斷記實際次數',()=>{const {b}=battle({feet:'breaker_boots'});b.player.stamina=0;const ctx={actor:b.player,target:b.enemy,move:D.moves.interrupt};R.effects.interrupt(b,ctx,{});near(b.player.stamina,0);b.enemy.cast={endAt:10};R.effects.interrupt(b,ctx,{});near(b.player.stamina,b.player.stats.stamina*.03);near(b.buildReport.sources.breaker_boots.staminaRecovered,b.player.stamina);const x=battle({},['unyielding']).b;x.choose('quick');R.effects.interrupt(x,{actor:x.enemy,target:x.player,move:D.moves.crush},{});assert.equal(x.buildReport.sources.unyielding.interruptsPrevented,1);});
test('費用修正按真正扣費統計；戰鬥重整保留報告，結算只合併一次',()=>{const {p,r,b}=battle({},['economy']);b.choose('lesser_heal');near(b.buildReport.manaSpent,D.moves.lesser_heal.cost.mana-b.buildReport.manaDelta);let raw;assert.ok(Save.save({setItem:(k,v)=>raw=v},{scene:'battle',run:r,permanent:p,build:r.build,battle:b,encounter:{type:'greywind_0',level:10}}));const loaded=Save.load({getItem:()=>raw});assert.equal(loaded.warning,undefined);const n=loaded.snapshot.battle;assert.deepEqual(n.buildReport,b.buildReport);J.commit(r,n);const before=JSON.stringify(r.buildReport);assert.equal(J.commit(r,n),false);assert.equal(JSON.stringify(r.buildReport),before);});
test('收藏目標跨存檔保存，結算記收穫，下局候選只含已擁有可配置內容',()=>{const p=P.freshProgress(),r=P.createRun(p);assert.equal(J.setTarget(p,'moves','spark'),true);assert.equal(J.target(p).owned,false);P.grantRewards(p,r,[{kind:'moves',id:'spark'},{kind:'books',id:'inferno'}]);assert.equal(J.target(p).owned,true);J.remember(p,r);assert.ok(J.candidates(p).some(x=>x.id==='spark'));assert.ok(!J.candidates(p).some(x=>x.kind==='books'));let raw;P.saveProgress({setItem:(k,v)=>raw=v},p);const restored=P.loadProgress({getItem:k=>k==='afterlight.progress.v2'?raw:null}).progress;assert.equal(J.target(restored).id,'spark');assert.ok(restored.meta.lastJourney.items.length);});
