const test=require('node:test'),assert=require('node:assert/strict');
const P=require('./progression'),C=require('./classes'),A=require('./achievements'),D=require('./data');
test('冒險者預設解鎖，戰士需以合格劍類戰鬥跨局累積解鎖',()=>{const p=P.freshProgress(),r=P.createRun(p);assert.deepEqual(p.unlockedClassIds,['ADVENTURER']);assert.throws(()=>C.select(p,P.defaultBuild(),'WARRIOR'));for(let i=0;i<50;i++){const run=P.createRun(p);A.start(run);const b={phase:'victory',events:[{type:'damage',actorId:'player',moveId:'quick',damage:1}]};A.battleEnd(p,run,b);}assert.ok(p.unlockedClassIds.includes('WARRIOR'));const b=P.defaultBuild();C.select(p,b,'WARRIOR');const r2=P.createRun(p,b);assert.equal(r2.activeClassId,'WARRIOR');assert.ok(P.statsFor(r2).hp>P.statsFor(r).hp);});
test('非劍傷害不累積劍之道路；專屬內容完成後只限戰士配置',()=>{const p=P.freshProgress(),r=P.createRun(p);A.start(r);A.battleEnd(p,r,{phase:'victory',events:[{type:'damage',actorId:'player',moveId:'fire',damage:1}]});assert.equal(p.achievementProgress.ACH_UNLOCK_WARRIOR||0,0);p.unlockedClassIds.push('WARRIOR');A.add(p,'ACH_WARRIOR_MASTERY_02',80);assert.ok(p.moves.WARRIOR_MOVE_001);const adventurer=P.defaultBuild();adventurer.moves=['quick','WARRIOR_MOVE_001'];assert.throws(()=>P.createRun(p,adventurer));const warrior={...P.defaultBuild(),activeClassId:'WARRIOR',moves:['quick','WARRIOR_MOVE_001']};assert.doesNotThrow(()=>P.createRun(p,warrior));});
test('裝備四個魔法傷害招式並由魔法累積擊倒五十名敵人才解鎖魔法師',()=>{const p=P.freshProgress(),r=P.createRun(p);r.build.moves=['fire','fireball','spark','blast_bolt'];for(let i=0;i<49;i++){A.start(r);A.battleEnd(p,r,{phase:'victory',events:[{type:'damage',actorId:'player',targetId:'enemy',moveId:'fire',damage:10}]});}assert.ok(!p.unlockedClassIds.includes('MAGE'));assert.equal(p.achievementProgress.ACH_UNLOCK_MAGE,49);A.start(r);A.battleEnd(p,r,{phase:'victory',events:[{type:'damage',actorId:'player',targetId:'enemy',moveId:'fire',damage:10}]});assert.ok(p.unlockedClassIds.includes('MAGE'));assert.equal(p.achievementProgress.ACH_UNLOCK_MAGE,50);});
test('少於四個魔法或最後一擊不是魔法時不解鎖魔法師',()=>{const p=P.freshProgress(),r=P.createRun(p);r.build.moves=['fire','fireball','spark','quick'];A.start(r);A.battleEnd(p,r,{phase:'victory',events:[{type:'damage',actorId:'player',targetId:'enemy',moveId:'fire',damage:10}]});assert.ok(!p.unlockedClassIds.includes('MAGE'));r.build.moves=['fire','fireball','spark','blast_bolt'];A.start(r);A.battleEnd(p,r,{phase:'victory',events:[{type:'damage',actorId:'player',targetId:'enemy',moveId:'quick',damage:10}]});assert.ok(!p.unlockedClassIds.includes('MAGE'));});
test('遊俠同時計算箭擊殺與命中讀條，聖職者同時計算實際治療與支援戰',()=>{const p=P.freshProgress(),r=P.createRun(p);p.achievementProgress.ACH_UNLOCK_RANGER=39;p.achievementProgress.ACH_UNLOCK_RANGER_CASTING_HITS=19;A.start(r);A.battleEnd(p,r,{phase:'victory',events:[{type:'damage',actorId:'player',targetId:'enemy',moveId:'RANGER_MOVE_001',damage:10,targetCasting:true}]});assert.ok(p.unlockedClassIds.includes('RANGER'));p.achievementProgress.ACH_UNLOCK_CLERIC=4990;p.achievementProgress.ACH_UNLOCK_CLERIC_SUPPORT_BATTLES=29;A.start(r);A.battleEnd(p,r,{phase:'victory',events:[{type:'cast',actorId:'player',moveId:'M096'},{type:'heal',actorId:'player',targetId:'player',moveId:'M096',healing:10},{type:'damage',actorId:'player',targetId:'enemy',moveId:'fire',damage:10}]});assert.ok(p.unlockedClassIds.includes('CLERIC'));});

test('法師四招可包含治療防護控制，保留既有擊殺進度；純SP招式不計入',()=>{const p=P.freshProgress(),r=P.createRun(p);p.achievementProgress.ACH_UNLOCK_MAGE=49;r.build.moves=['fire','lesser_heal','protect','freeze'];A.start(r);A.battleEnd(p,r,{phase:'victory',events:[{type:'damage',actorId:'player',targetId:'enemy',moveId:'fire',damage:10}]});assert.equal(p.achievementProgress.ACH_UNLOCK_MAGE,50);assert.ok(p.unlockedClassIds.includes('MAGE'));const other=P.freshProgress();r.build.moves=['fire','haste','freeze','focus'];A.start(r);A.battleEnd(other,r,{phase:'victory',events:[{type:'damage',actorId:'player',targetId:'enemy',moveId:'fire',damage:10}]});assert.equal(other.achievementProgress.ACH_UNLOCK_MAGE||0,0);});
