const test=require('node:test'),assert=require('node:assert/strict'),P=require('./progression'),D=require('./data'),R=require('./skill-runtime'),Save=require('./run-save');
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
function build(cls,weapon='sword',skills=[]){const p=P.freshProgress();p.unlockedClassIds.push(cls);p.equipment.push(weapon);p.skills.push(...skills);const b={...P.defaultBuild(),activeClassId:cls,talents:skills,equipment:{head:null,chest:null,arms:null,feet:null,weapon}},r=P.createRun(p,b),encounter={type:'greywind_0',level:9},battle=P.battleFor(r,encounter,()=>.99);return {p,r,battle,encounter};}
test('戰士使用劍或鈍器中斷成功率乘0.9，弓杖及冒險者沒有加成',()=>{for(const weapon of ['sword','mace','bow','ash_staff']){const {battle:b}=build('WARRIOR',weapon);close(b.player.runtime.modify('incomingInterruptChance',1),['sword','mace'].includes(weapon)?.9:1);}const {battle:a}=build('ADVENTURER');close(a.player.runtime.modify('incomingInterruptChance',1),1);});
test('戰士抗性改變真正的中斷結果，仍扣費且不阻擋傷害',()=>{const {battle:b}=build('WARRIOR');b.choose('quick');b.rng=()=>.95;const context={actor:b.enemy,target:b.player,move:D.moves.crush};const cast=b.player.cast,sp=b.player.stamina;assert.equal(R.effects.interrupt(b,context,{}),false);assert.equal(b.player.cast,cast);assert.equal(b.player.stamina,sp);const hp=b.player.hp;b.receiveDamage(b.enemy,b.player,10,D.moves.crush);close(b.player.hp,hp-10);b.rng=()=>.89;R.effects.interrupt(b,context,{});assert.equal(b.player.cast,null);});
test('抗性與霸體互相獨立：抗性成功不消耗一次霸體',()=>{const {battle:b}=build('WARRIOR','sword',['unyielding']);b.choose('quick');const c={actor:b.enemy,target:b.player,move:D.moves.crush};b.rng=()=>.95;R.effects.interrupt(b,c,{});assert.equal(b.player.runtime.once.size,0);b.rng=()=>.5;R.effects.interrupt(b,c,{});assert.ok(b.player.cast);assert.equal(b.player.runtime.once.size,1);R.effects.interrupt(b,c,{});assert.equal(b.player.cast,null);});
test('遊俠弓箭讀條與條件爆擊實際生效，非弓或非箭不加成',()=>{for(const weapon of ['bow','sword']){const {battle:b}=build('RANGER',weapon);close(b.getMove('metal_1').attackTime,D.moves.metal_1.attackTime*(weapon==='bow'?.92:1));close(b.getMove('quick').attackTime,D.moves.quick.attackTime);const baseline=b.rule('critChance',b.player,{move:D.moves.quick}),castCrit=b.rule('critChance',b.player,{move:D.moves.metal_1});close(castCrit,baseline+(weapon==='bow'?.05:0));b.enemy.cast=null;close(b.rule('critChance',b.player,{move:D.moves.metal_1}),baseline);}});
test('遊俠天生效果和弓術一起計算，不占技能槽',()=>{const {battle:b,r}=build('RANGER','bow',['archery']),m=b.getMove('metal_1');const base=b.rules.critChance(b.player.stats);close(b.rule('critChance',b.player,{move:m}),base+.08+.05);assert.equal(r.build.talents.length,1);assert.ok(b.player.runtime.sources.some(s=>s.id==='trait_hunter_instinct'));});
test('天生效果在戰鬥存檔恢復後只套一次',()=>{const {p,r,battle,encounter}=build('RANGER','bow'),expected=battle.getMove('metal_1').attackTime;let raw;Save.save({setItem(k,v){raw=v;}},{scene:'battle',run:r,permanent:p,build:r.build,battle,encounter});const saved=Save.load({getItem(){return raw;}});assert.equal(saved.warning,undefined);close(saved.snapshot.battle.getMove('metal_1').attackTime,expected);assert.equal(saved.snapshot.battle.player.runtime.sources.filter(s=>s.id==='trait_hunter_instinct').length,1);});
