/* Explicit developer fixture factory; it never mutates permanent progress. */
(function(root){
 const D=typeof module!=='undefined'?require('./data.js'):root.GameData;
 const C=typeof module!=='undefined'?require('./engine.js'):root.BattleCore;
 const R=typeof module!=='undefined'?require('./skill-runtime.js'):root.SkillRuntime;
 function build(config={}){
  const loadout={talents:config.talents||[],moves:config.moves||['fireball','heavy_slash','double_slash','freeze'],ultimate:config.ultimate===null?null:config.ultimate||'nova',equipment:{head:null,chest:null,arms:null,feet:null,weapon:'sword',...config.equipment}};
  if(loadout.talents.some(id=>!D.skills[id]))throw Error('未知技能');C.validateBuild(loadout);
  for(const [slot,id]of Object.entries(loadout.equipment))if(id&&D.equipment[id]?.slot!==slot)throw Error('裝備欄位錯誤');
  for(const element of [...(config.elements||[]),...(config.enemyElements||[])])if(!D.elements[element])throw Error('未知屬性');
  const stats={hp:1000,mana:100,stamina:100,agility:40,luck:10,...config.stats};
  if(config.applyStatBonuses){for(const id of Object.values(loadout.equipment))for(const [k,v]of Object.entries(D.equipment[id]?.modifiers||{}))stats[k]+=v;const rates={};for(const id of loadout.talents){for(const [k,v]of Object.entries(D.skills[id].modifiers||{}))stats[k]+=v;for(const [k,v]of Object.entries(D.skills[id].statRates||{}))rates[k]=(rates[k]||0)+v;}for(const [k,v]of Object.entries(rates))stats[k]*=1+v;}
  const gearEffects={};for(const id of Object.values(loadout.equipment))for(const key of ['physicalMultiplier','physicalAttackTime','onDodgeShorten'])if(D.equipment[id]?.[key])gearEffects[key]=D.equipment[id][key];
  const b=new C.Battle({build:loadout,stats,elements:config.elements||[],enemy:{name:'測試守衛',stats:{hp:100000,mana:100,stamina:25,agility:0,luck:0},moves:['crush'],elements:config.enemyElements||[]},rng:config.rng||Math.random,rules:{critChance:config.critChance??0,dodgeChance:config.dodgeChance??0,critMultiplier:1.5},equipmentEffects:{...gearEffects,...config.equipmentEffects}});
  b.run.debuffIds=(config.injuries||[]).slice();b.start();
  for(const [key,value]of Object.entries(config.resources||{})){if(!['hp','mana','stamina'].includes(key)||!Number.isFinite(value))throw Error('資源數值無效');b.player[key]=Math.max(key==='hp'?1:0,Math.min(b.player.stats[key],value));}
  const chargeCost=D.moves[loadout.ultimate]?.ultimateChargeCost||100;b.charge=Math.max(0,Math.min(chargeCost,(config.charge||0)/100*chargeCost));
  for(const entry of config.statuses||[]){if(!['player','enemy'].includes(entry.target)||!entry.status?.id||!Number.isFinite(entry.status.duration))throw Error('狀態格式無效');R.applyStatus(b,b[entry.target],entry.status,b.player);}
  return b;
 }
 function form(active=false){const options=(list,selected)=>'<option value="">無</option>'+list.map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${x.name}${x.subtitle?' · '+x.subtitle:''}</option>`).join('');
  return `<h2 id="modal-title">戰鬥測試工作台</h2><p>建立獨立測試戰鬥，不寫入永久收藏。進入後以右上暫停返回此頁，可重新指定測試狀態。</p><div class="debug-fields">${Array.from({length:4},(_,i)=>`<label>技能 ${i+1}<select id="lab-skill-${i}">${options(Object.values(D.skills).filter(s=>s.category!=='legacy'),['economy','afterimage','chill','earth_body'][i])}</select></label>`).join('')}${Array.from({length:4},(_,i)=>`<label>招式 ${'ABCD'[i]}<select id="lab-move-${i}">${options(Object.values(D.moves).filter(m=>m.kind==='normal'),['fireball','heavy_slash','double_slash','water_0'][i])}</select></label>`).join('')}<label>大絕<select id="lab-ultimate">${options(Object.values(D.moves),'nova')}</select></label>${['head','chest','arms','feet','weapon'].map(slot=>`<label>${({head:'頭',chest:'胸',arms:'手',feet:'腳',weapon:'武器'})[slot]}<select id="lab-gear-${slot}">${options(Object.values(D.equipment).filter(e=>e.slot===slot),slot==='weapon'?'sword':'')}</select></label>`).join('')}${[['hp','HP',1000],['mana','MP',100],['stamina','SP',100],['agility','敏捷',40],['charge','大絕 %',0],['physical','物理裝備倍率',1],['attack','裝備攻擊時間加值',0]].map(([id,name,value])=>`<label>${name}<input id="lab-${id}" type="number" value="${value}" step="any" min="0"></label>`).join('')}<label>玩家屬性<select id="lab-element">${options(Object.entries(D.elements).map(([id,name])=>({id,name})))}</select></label><label>敵方屬性<select id="lab-enemy-element">${options(Object.entries(D.elements).map(([id,name])=>({id,name})))}</select></label><label>敵方第二屬性<select id="lab-enemy-element2">${options(Object.entries(D.elements).map(([id,name])=>({id,name})))}</select></label></div><label>狀態 JSON（可不填）<textarea id="lab-statuses" rows="4" placeholder='[{"target":"enemy","status":{"id":"chill","name":"寒氣","duration":4,"polarity":"debuff","modifiers":[{"stage":"agility","op":"multiply","value":0.9}]}}]'></textarea></label><div class="modal-footer">${active?'<button class="secondary-button" data-action="debug-end">結束測試</button>':''}<button class="secondary-button" data-action="close">取消</button><button class="primary-button" data-action="debug-start">開始測試</button></div>`;
 }
 const api={build,form};if(typeof module!=='undefined')module.exports=api;else root.GameDebug=api;
})(globalThis);
