const test=require('node:test'),assert=require('node:assert/strict');
const P=require('./progression'),D=require('./data'),R=require('./skill-runtime'),Lab=require('./debug-lab'),Save=require('./run-save');
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
function lab(moves,talents=[]){const b=Lab.build({moves,talents,rng:()=>.99});b.enemy.cast.endAt=999;return b;}
function cast(b,id){assert.ok(b.choose(id).ok);b.advance(b.player.cast.duration+((D.moves[id].hits||1)-1)*.18+.001);}
test('正式敌人减速延長後續讀條，狀態到期恢復原速度',()=>{const r=P.createRun(P.freshProgress()),b=P.battleFor(r,{type:'greywind_0',level:9},()=>.99),m=b.getMove(b.enemyDefinition.moves[0],b.enemy),base=b.castDuration(m,b.enemy);R.applyStatus(b,b.enemy,{id:'slow',name:'束縛',duration:4,modifiers:[{stage:'agility',value:.75,op:'multiply'}]},b.player);close(b.castDuration(m,b.enemy),base/.75);b.advance(4.001);close(b.castDuration(m,b.enemy),base);});
test('凍結阻止出招，暫停既有讀條與連擊，結束恢復且有短暫抗性',()=>{const b=lab(['freeze']);b.enemy.cast.endAt=3;const c={actor:b.player,target:b.enemy,move:D.moves.freeze};R.effects.freeze(b,c,{duration:1});close(b.enemy.cast.endAt,4);assert.equal(b.begin(b.enemy,'crush').ok,false);b.advance(.99);assert.ok(b.isFrozen(b.enemy));b.advance(.02);assert.equal(b.isFrozen(b.enemy),false);assert.equal(R.effects.freeze(b,c,{duration:1}),false);b.advance(3.1);assert.equal(R.effects.freeze(b,c,{duration:1}),true);b.enemy.cast=null;b.enemy.sequence={nextAt:9};b.enemy.freezeImmuneUntil=0;R.effects.freeze(b,c,{duration:1});close(b.enemy.sequence.nextAt,10);});
test('冰凍魔法與冰封實際停止敵人行動，Boss凍結減半',()=>{for(const id of ['freeze','M083']){const b=lab([id]);cast(b,id);assert.ok(b.isFrozen(b.enemy));const duration=D.moves[id].effects.find(e=>e.type==='freeze').duration;assert.ok(b.enemy.statuses.frozen.expiresAt-b.time<duration);const boss=lab([id]);boss.enemyDefinition.balanceRole='boss';cast(boss,id);close(boss.enemy.statuses.frozen.duration,duration*.5);}});
test('反擊架勢減傷並反擊，雙方架勢不遞迴，持續傷害與致死不反擊',()=>{const b=lab(['counter_stance']);cast(b,'counter_stance');const hp=b.enemy.hp,playerHp=b.player.hp;R.applyStatus(b,b.enemy,{id:'counter_guard',name:'反擊架勢',duration:4,counterRatio:.25,modifiers:[]},b.enemy);const move={id:'test',damageType:'physical',elements:[]};b.receiveDamage(b.enemy,b.player,100*.75,move);close(playerHp-b.player.hp,75);close(hp-b.enemy.hp,18.75);assert.equal(b.events.filter(e=>e.text==='反擊架勢反擊').length,1);b.receiveDamage(b.enemy,b.player,10,move,false,true);close(hp-b.enemy.hp,18.75);b.player.hp=1;b.receiveDamage(b.enemy,b.player,10,move);close(hp-b.enemy.hp,18.75);});
test('毒芽造成五次中毒傷害、刷新不疊層；吸魂按實際傷害回HP',()=>{const b=lab(['M078','M099']);cast(b,'M078');const hp=b.enemy.hp,t=b.time;assert.ok(b.enemy.statuses.poison);b.advance(5);close(hp-b.enemy.hp,100*.025*5);assert.ok(b.time>t);b.player.hp=100;const before=b.player.hp;cast(b,'M099');const hit=b.events.filter(e=>e.type==='damage'&&e.moveId===D.moves.M099.id).at(-1);close(b.player.hp-before,hit.damage*.2);});
test('蓄力只強化下一個傷害招式，輔助不消耗，多段整招強化',()=>{const b=lab(['charge_up','focus','double_slash']);cast(b,'charge_up');cast(b,'focus');assert.ok(b.player.statuses.charged);const expected=b.preview('double_slash').estimatedDamage;cast(b,'double_slash');assert.equal(b.player.statuses.charged,undefined);close(b.events.filter(e=>e.type==='damage'&&e.moveId==='double_slash').reduce((n,e)=>n+e.damage,0),expected);close(b.preview('double_slash').estimatedDamage,expected/1.35);});
test('泥濘牽制識別三種束縛，過期和不相關狀態不觸發',()=>{for(const id of ['root','magnetic_bind','sand_bind']){const b=lab(['water_0'],['S060']),base=b.preview('water_0').estimatedDamage;R.applyStatus(b,b.enemy,{id,name:'束縛',duration:1,modifiers:[]},b.player);close(b.preview('water_0').estimatedDamage,base*1.12);b.advance(1.01);close(b.preview('water_0').estimatedDamage,base);}});
test('滿溢魔力按施放前MP判定，扣費跌破80%不丟加成',()=>{const b=lab(['mana_bolt'],['overflowing_mana']);b.player.mana=80;const expected=b.preview('mana_bolt').estimatedDamage;cast(b,'mana_bolt');assert.ok(b.player.mana<80);close(b.events.find(e=>e.type==='damage').damage,expected);});
test('神聖回流只在治療或防護成功後恢復，控制魔法不回復',()=>{const b=lab(['freeze','protect'],['CLERIC_SKILL_002']);b.player.mana=50;const cost=b.getMove('freeze').cost.mana;cast(b,'freeze');close(b.player.mana,50-cost);const before=b.player.mana,cost2=b.getMove('protect').cost.mana;cast(b,'protect');close(b.player.mana,before-cost2+5);});
test('持續傷害保留元素，防護與元素抗性生效',()=>{const b=lab(['M078']);b.enemy.runtime=new R.Runtime(b,b.enemy,[D.skills.element_wood_resistance]);cast(b,'M078');const hp=b.enemy.hp;b.advance(1);close(hp-b.enemy.hp,2.5*.85);});
test('登錄效果及技能修正皆有執行入口，無空白技能或控制招式',()=>{const stages=new Set(['damage','attackTime','critChance','interruptChance','cost:mana','incoming','healing','critMultiplier','exp','cost:stamina','chargeRate','dodgeChance']),events=new Set(['OnPhysicalSkillFinished','OnCriticalHit','OnInterruptReceived','OnDamageTaken','OnDodge','OnInterruptSuccess','OnSkillCastFinished','OnDamageDealt','OnHPChanged','OnLethalDamage','OnMagicSkillFinished']);for(const s of new Set(Object.values(D.skills))){for(const m of s.combatModifiers||[])assert.ok(stages.has(m.stage),s.name);for(const h of s.hooks||[]){assert.ok(events.has(h.event),s.name);for(const e of h.effects)assert.ok(R.effects[e.type],s.name);}}for(const m of new Set(Object.values(D.moves)))for(const e of m.effects||[])assert.ok(R.effects[e.type],m.name);});
test('凍結中的戰鬥存檔恢復保留停止行動與抗性時間',()=>{const p=P.freshProgress(),r=P.createRun(p),encounter={type:'greywind_0',level:9},b=P.battleFor(r,encounter,()=>.99);R.effects.freeze(b,{actor:b.player,target:b.enemy,move:D.moves.freeze},{duration:1});let raw;Save.save({setItem(k,v){raw=v;}},{scene:'battle',run:r,permanent:p,build:r.build,encounter,battle:b});const restored=Save.load({getItem(){return raw;}});assert.equal(restored.warning,undefined);assert.ok(restored.snapshot.battle.isFrozen(restored.snapshot.battle.enemy));assert.equal(restored.snapshot.battle.enemy.freezeImmuneUntil,b.enemy.freezeImmuneUntil);});

test('生命轉化確實回血，規格物理箭類使用SP與物理加成',()=>{const b=lab(['wood_4','metal_1']);b.player.hp=100;cast(b,'wood_4');close(b.player.hp,300);assert.ok(b.player.statuses.wood_ward);for(const m of new Set(Object.values(D.moves)))if(m.specKind==='physical'){assert.equal(m.damageType,'physical',m.name);assert.ok(m.cost.stamina>0,m.name);}const before=b.preview('metal_1').estimatedDamage;b.player.runtime=new R.Runtime(b,b.player,[D.skills.swordsmanship]);close(b.preview('metal_1').estimatedDamage,before*1.12);});
