/* Cosmetic counters only. Progression grants all stats before this panel opens. */
(function(root){
 const labels={hp:'生命 HP',mana:'魔力 MP',stamina:'體力 SP',agility:'敏捷',luck:'運氣'};
 const format=n=>Number(n.toFixed(1)).toLocaleString('zh-TW');
 const DURATION=2.05;
 function value(from,to,time,delay=0,reduced=false){if(reduced)return to;const t=Math.max(0,Math.min(1,(time-delay)/DURATION));const eased=1-Math.pow(1-t,3.25);return from+(to-from)*eased;}
 function milestones(exp){const marks=[];for(let n=Math.ceil((exp.beforeLevel+1)/10)*10;n<=exp.afterLevel;n+=10)if(n%100===0||n===500)marks.push(n);else if(n%50===0)marks.push(n);return marks;}
 function html(exp){if(!exp.beforeStats||!exp.afterStats)return '';const marks=milestones(exp),cap=exp.afterLevel>=exp.maxLevel;return `<section id="growth-celebration" class="growth-celebration racing ${exp.levels>1?'multi-level':''}" aria-label="本次升級提升"><div class="growth-burst" aria-hidden="true"><i></i><i></i><i></i></div><div class="growth-kicker">能力提升</div><div class="growth-level"><small>HP ${format(exp.beforeStats.hp)}</small><span class="growth-arrow">›</span><strong id="growth-level-number" aria-hidden="true">${format(exp.beforeStats.hp)}</strong><b>＋<span id="growth-level-gain">0</span> HP</b></div>${cap?`<div class="growth-milestone cap">能力成長已達上限</div>`:marks.length?`<div class="growth-milestone">五項能力大幅成長</div>`:''}<p class="growth-caption">五項能力同步提升</p><div class="growth-stats">${Object.entries(labels).map(([key,label],i)=>`<div class="growth-row" style="--row:${i}"><i></i><span>${label}</span><small>${format(exp.beforeStats[key])}</small><em>›</em><strong id="growth-${key}" aria-hidden="true">${format(exp.beforeStats[key])}</strong><b>＋<span id="growth-${key}-gain">0</span></b><span class="sr-only">提升至 ${format(exp.afterStats[key])}</span></div>`).join('')}</div></section>`;}
 function set(id,value){const node=document.getElementById(id);if(node)node.textContent=value;}
 function update(exp,time,reduced=false){if(!exp.beforeStats||!exp.afterStats)return;const done=reduced||time>=DURATION+.55,box=document.getElementById('growth-celebration');if(box&&box.classList){box.classList.toggle('racing',!done);box.classList.toggle('landed',done);}set('growth-level-number',String(Math.round(value(exp.beforeStats.hp,exp.afterStats.hp,time,0,reduced))));set('growth-level-gain',String(Math.round(value(0,exp.afterStats.hp-exp.beforeStats.hp,time,.04,reduced))));Object.keys(labels).forEach((key,i)=>{const delay=.12+i*.075,delta=exp.afterStats[key]-exp.beforeStats[key];set('growth-'+key,format(value(exp.beforeStats[key],exp.afterStats[key],time,delay,reduced)));set('growth-'+key+'-gain',format(value(0,delta,time,delay+.04,reduced)));});}
 const api={DURATION,value,milestones,html,update};if(typeof module!=='undefined')module.exports=api;else root.LevelUp=api;
})(globalThis);
