const test=require('node:test'),assert=require('node:assert/strict');
const D=require('./data'),M=require('./world-maps'),R=require('./map-routes'),P=require('./progression'),W=require('./world');
const make=()=>{const r=P.createRun(P.freshProgress(),undefined,()=>.5);r.adventurerRank.index=17;r.battleStats.clearedDungeonIds=D.dungeons.map(d=>d.id);return r;};
test('35 張正式圖四象限各有目的地，地下城 ID 保留、空象限只有一深入點',()=>{for(const map of M.maps){assert.equal(map.route.destinations.length,4);for(let q=0;q<4;q++){const ds=map.dungeonIds.map(id=>D.dungeons.find(d=>d.id===id)).filter(d=>d.quadrant===q),ps=map.deepPoints.filter(p=>p.quadrant===q);assert.equal(ds.length+ps.length,1);assert.equal(ps.length,ds.length?0:1);}for(const [i,branch]of map.route.branches.entries()){assert.ok(map.route.mainRoad.some(p=>R.dist(p,branch[0])<1e-8));assert.ok(R.dist(branch.at(-1),map.route.destinations[i])<1e-8);}}});
test('同區相鄰主路出入口精確對接，安全落點雙向有效',()=>{const r=make();for(const region of M.regions)for(let i=0;i<4;i++){const a=D.maps[region.mapIds[i]],b=D.maps[region.mapIds[i+1]];assert.equal(a.route.portals.departure.y,b.route.portals.arrival.y);M.enter(r,a.id);const exit=a.route.portals.departure;r.position={x:a.width-40,y:exit.y};assert.equal(W.edgeExit(r).entity.id,b.id);M.enter(r,b.id,{edge:'right'});assert.deepEqual(r.position,R.arrival(b,true));assert.ok(R.safe(r.position,b));r.position={x:40,y:b.route.portals.arrival.y};assert.equal(W.edgeExit(r).entity.id,a.id);M.enter(r,a.id,{edge:'left'});assert.deepEqual(r.position,R.arrival(a,false));assert.ok(R.safe(r.position,a));}});
test('中央和門前禁止刷怪，各段等級固定，前圖主路銜接下一圖低段',()=>{for(const region of M.regions)for(const [i,id]of region.mapIds.entries()){const map=D.maps[id];assert.ok(map.spawnPoints.length>=60&&map.spawnPoints.length<=72);for(const p of map.spawnPoints){assert.equal(R.safe(p,map),false);const band=p.elite?map.eliteLevelRange:map.route.bands[p.section];assert.ok(p.level>=band[0]&&p.level<=band[1]);}assert.equal(map.spawnPoints.filter(p=>p.elite).length,4);for(const section of ['arrival','main','deep'])assert.ok(map.spawnPoints.filter(p=>p.section===section).length>=8);if(i)assert.equal(D.maps[region.mapIds[i-1]].route.bands.main[1],map.route.bands.arrival[0]);}});
test('入口與中央路線可步行，不會因背景樹石堵路',()=>{for(const map of M.maps){for(const road of map.route.roads)for(let i=1;i<road.length;i++)for(let t=.01;t<.99;t+=.07){const a=road[i-1],b=road[i];const x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;if(x>=35&&x<=map.width-35)assert.equal(W.blocked(x,y,map.id),false,map.id);}for(const forward of [true,false]){const point=R.arrival(map,forward);assert.equal(W.blocked(point.x,point.y,map.id),false);}}});
test('非出入口的邊界不跨圖，通行條件仍使用 B／A／S',()=>{const r=make(),map=D.maps.north_plains_2;M.enter(r,map.id);r.position={x:map.width-40,y:200};assert.equal(W.edgeExit(r),null);r.position={x:3000,y:40};assert.equal(W.edgeExit(r),null);r.adventurerRank.index=0;assert.equal(M.enter(r,'north_plains_3'),false);});
test('敵人追擊與刷新不能侵入中央或入口安全區',()=>{const r=make(),map=D.maps[r.currentMapId],gate=R.arrival(map,true),enemy=r.world.enemies.find(e=>e.id.includes('-patrol-')&&!e.elite);enemy.type=map.enemyPoolIds.find(id=>D.monsters[id].behavior!=='neutral');for(const p of [map.entry,gate]){r.position={...p};Object.assign(enemy,{x:p===gate?910:p.x+460,y:p.y,homeX:p===gate?910:p.x+460,homeY:p.y,defeatedUntil:0});for(let i=0;i<40;i++)W.update(r,.05,{x:0,y:0});assert.equal(enemy.alert,false);assert.equal(R.safe(enemy,map),false);assert.equal(W.update(r,.05,{x:0,y:0}),null);}Object.assign(enemy,{...map.spawnPoints[0],homeX:map.spawnPoints[0].x,homeY:map.spawnPoints[0].y,defeatedUntil:r.world.time+1});r.position={...gate};W.update(r,2,{x:0,y:0});assert.equal(R.safe(enemy,map),false);});
test('遷移舊巡邏配置保留死亡冷卻、玩家位置、成長、收藏與藏書進度',()=>{const r=make(),enemy=r.world.enemies.find(e=>e.id.includes('-patrol-'));r.world.enemies.push({id:'event-sentinel',mapId:r.currentMapId,type:enemy.type,x:4000,y:2500,homeX:4000,homeY:2500,level:42,specialEvent:true,defeatedUntil:123});r.mapLayoutVersion=5;r.level=42;r.exp=123;r.ultimateCharge=63;r.position={x:4000,y:2500};r.mapPositions.north_plains_2={x:4500,y:2300};enemy.x=enemy.homeX=1;enemy.y=enemy.homeY=1;enemy.defeatedUntil=999;enemy.discovered=true;const values=JSON.stringify([r.level,r.exp,r.ultimateCharge,r.position,r.mapPositions,r.build,r.loot,r.exploration]);M.ensureRun(r);assert.ok(r.world.enemies.some(e=>e.id==='event-sentinel'&&e.defeatedUntil===123));assert.equal(enemy.defeatedUntil,999);assert.equal(enemy.discovered,true);assert.equal(R.safe(enemy,D.maps[enemy.mapId]),false);assert.equal(JSON.stringify([r.level,r.exp,r.ultimateCharge,r.position,r.mapPositions,r.build,r.loot,r.exploration]),values);const saved=JSON.stringify(r);M.ensureRun(r);assert.equal(JSON.stringify(r),saved);});
test('新手隨機圖與首次教學不使用正式路線安全區或深入點',()=>{for(const map of M.starterMaps){assert.equal(map.route,null);assert.equal(map.deepPoints.length,0);assert.equal(map.spawnPoints.length,18);assert.equal(R.safe(map.entry,map),false);}const T=require('./training-map');assert.equal(D.maps.tutorial_court.route,undefined);});

test('稀疏野地配置：道路淨空、至少四分之三離路、最小間距與四象限覆蓋',()=>{for(const map of M.maps){const points=map.spawnPoints;assert.ok(points.filter(p=>R.roadDistance(p,map.route.roads)>R.rules.roadsideDistance).length/points.length>=.75,map.id);for(let i=0;i<points.length;i++){const p=points[i];assert.ok(R.roadDistance(p,map.route.roads)>=260);assert.ok(map.route.destinations.every(d=>R.dist(p,d)>=280));for(let j=i+1;j<points.length;j++)assert.ok(R.dist(p,points[j])>=360,map.id);}for(let q=0;q<4;q++){const group=points.filter(p=>p.quadrant===q);assert.ok(group.length>=12&&group.length<=18,map.id);assert.equal(group.filter(p=>p.elite).length,1);}assert.ok(points.filter(p=>p.elite).every(p=>p.section==='deep'&&p.habitat==='field'));}});
test('上一版180個生成點縮減後，刪除多餘點並保留冷卻與玩家進度',()=>{const r=make(),map=D.maps[r.currentMapId];r.mapLayoutVersion=6;const retained=r.world.enemies.find(e=>e.id===map.id+'-patrol-0');retained.defeatedUntil=987;for(let i=map.spawnPoints.length;i<180;i++)r.world.enemies.push({...retained,id:map.id+'-patrol-'+i});const before=JSON.stringify([r.level,r.exp,r.build,r.loot,r.position]);M.ensureRun(r);assert.equal(r.world.enemies.filter(e=>e.id.startsWith(map.id+'-patrol-')).length,map.spawnPoints.length);assert.equal(retained.defeatedUntil,987);assert.equal(JSON.stringify([r.level,r.exp,r.build,r.loot,r.position]),before);for(const e of r.world.enemies.filter(e=>e.id.startsWith(map.id+'-patrol-'))){const index=Number(e.id.split('-patrol-')[1]),point=map.spawnPoints[index],pool=point.elite?map.elitePoolIds:map.enemyPoolIds;assert.equal(e.type,pool[index%pool.length]);}});
