(function(root){
 const M=root.GameMeta,D=root.GameData,U=root.GameUI;
 const header=(title,sub)=>`<header class="screen-header"><div><div class="eyebrow">${sub}</div><h1>${title}</h1></div>${U.button('返回','screen-back')}</header>`;
 const label=d=>`<strong>${U.escape(d.name)}</strong>${d.subtitle&&d.subtitle!==d.name?`<small>${U.escape(d.subtitle)}</small>`:''}`;
 function shop(game){const p=game.permanent,s=M.stock(p),t=M.tier(p),m=p.meta,remaining=Math.max(0,(s.epoch+1)*M.PERIOD-Date.now()),hours=Math.floor(remaining/3600000),minutes=Math.floor(remaining/60000)%60;
  return `${header('旅者商店','THE TRAVELLING MERCHANT')}<div class="meta-scroll"><div class="meta-banner"><div><small>旅者徽記</small><strong>◇ ${m.marks}</strong></div><span>每 12 小時換新<br><b id="shop-countdown">${hours} 小時 ${minutes} 分後刷新</b></span></div><p class="quiet-note">已攻略 ${t.count} 座不同地下城 · ${t.slots} 個貨架<br>${t.index<3?`通關 ${M.tiers[t.index+1].clears} 座後解鎖 ${M.tiers[t.index+1].slots} 格與更多商品`:'旅者商店貨架已全數開放'}<br>購買後永久學會，出發前可配置。</p><div class="merchant-grid">${s.items.map(key=>{const c=M.catalog.find(x=>x.key===key),pool=c.kind==='moves'?D.moves:D.skills,d=pool[c.id]||Object.values(pool).find(x=>x.contentId===c.id),has=M.owned?M.owned(p,c):c.kind==='moves'?!!p.moves[c.id]:p.skills.includes(c.id);return `<article class="merchant-card ${has?'collected':''}"><span class="meta-glyph">${U.icon(d.icon||'star',30)}</span><div class="meta-item-name"><small>${c.kind==='moves'?'招式 · Lv.1':'被動技能'}</small>${label(d)}</div><p>${U.escape(d.description||'可在角色設定查看招式資訊。')}</p>${c.kind==='moves'?`<small class="quiet-note">${U.cost(d)}</small>`:''}<button class="ui-button ${has?'':'primary'}" data-action="shop-buy" data-id="${c.key}" data-epoch="${s.epoch}" ${has||m.marks<c.price?'disabled':''}>${has?'已永久解鎖':`◇ ${c.price} · ${m.marks<c.price?'徽記不足':'解鎖'}`}</button></article>`;}).join('')||'<div class="meta-empty">目前商品池已全部蒐集。<br>攻略更多地下城，解鎖新貨源。</div>'}</div><p class="quiet-note">擊敗敵人、首次發現地下城與通關可累積徽記；整局結束時帶回，失敗也保留。<br>每件商品只需解鎖一次，已有能力不會重複販售。</p>${U.button('配置已學會的能力','setup')}</div>`;
 }
 function codex(game){const all=M.collection(game.permanent),tab=['moves','skills','monsters','dungeons'].includes(game.codexTab)?game.codexTab:'moves',list=all[tab],total=Object.values(all).flat(),known=total.filter(x=>x.known).length;
  return `${header('旅途圖鑑','TRACES OF THE UNKNOWN')}<div class="meta-scroll"><div class="meta-banner"><div><small>已發現與蒐集</small><strong>${known} <small>/ ${total.length}</small></strong></div><span>尚有 ${total.length-known} 項未知<br>每段旅途，都留下足跡</span></div><div class="codex-progress"><i style="width:${100*known/Math.max(1,total.length)}%"></i></div><nav class="codex-tabs" aria-label="圖鑑分類">${[['moves','招式'],['skills','技能'],['monsters','怪物'],['dungeons','地下城']].map(([id,name])=>`<button data-action="codex-tab" data-id="${id}" class="${tab===id?'selected':''}">${name}<small>${all[id].filter(x=>x.known).length} / ${all[id].length}</small></button>`).join('')}</nav><div class="codex-grid">${list.map((e,i)=>`<article class="codex-entry ${e.known?'known':'unknown'}"><span class="meta-glyph" aria-hidden="true">${e.known?U.icon(e.data.icon||(tab==='monsters'?'hood':'book'),28):'?'}</span><div><small>No. ${String(i+1).padStart(3,'0')} · ${e.known?tab==='monsters'?(e.complete?'已擊敗':'已遇見'):tab==='dungeons'?(e.complete?'已通關':e.entered?'已進入':'已發現'):'已永久學會':'尚未發現'}</small>${e.known?label(e.data):'<strong>未知的'+({moves:'招式',skills:'技能',monsters:'生物',dungeons:'遺跡'}[tab])+'</strong>'}<p>${U.escape(e.known?(e.data.description||e.data.features?.join(' ／ ')||'已記錄於旅途圖鑑。'):e.hint)}</p></div></article>`).join('')}</div></div>`;
 }
 function settlement(run){const r=M.ledger(run);return `<section class="meta-settlement"><small>本局帶回 · 旅者徽記</small><strong>＋${r.total} ◇</strong><p>戰鬥 ${r.combat} · 探索 ${r.exploration} · 地下城 ${r.dungeons}</p><small>已存入局外商店錢包</small></section>`;}
 root.MetaScreens={shop,codex,settlement};
})(globalThis);
