(function(root){
 const M=root.GameMeta,D=root.GameData,U=root.GameUI;
 const header=(title,sub)=>`<header class="screen-header"><div><div class="eyebrow">${sub}</div><h1>${title}</h1></div>${U.button('返回','screen-back')}</header>`;
 const label=d=>`<strong>${U.escape(d.name)} ${U.gradeBadge(d)}</strong>${d.subtitle&&d.subtitle!==d.name?`<small>${U.escape(d.subtitle)}</small>`:''}`;
 function shop(game){const p=game.permanent,s=M.stock(p),t=M.tier(p),m=p.meta,remaining=Math.max(0,(s.epoch+1)*M.PERIOD-Date.now()),hours=Math.floor(remaining/3600000),minutes=Math.floor(remaining/60000)%60;
  return `${header('旅者商店','THE TRAVELLING MERCHANT')}<div class="meta-scroll"><div class="meta-banner"><div><small>旅者徽記</small><strong>◇ ${m.marks}</strong></div><span>每 12 小時換新<br><b id="shop-countdown">${hours} 小時 ${minutes} 分後刷新</b></span></div><p class="quiet-note">已攻略 ${t.count} 座不同地下城 · ${t.slots} 個貨架<br>${t.index<3?`通關 ${M.tiers[t.index+1].clears} 座後解鎖 ${M.tiers[t.index+1].slots} 格與更多商品`:'旅者商店貨架已全數開放'}<br>購買後永久學會，出發前可配置。</p><div class="merchant-grid">${s.items.map(key=>{const c=M.catalog.find(x=>x.key===key),pool=c.kind==='moves'?D.moves:D.skills,d=pool[c.id]||Object.values(pool).find(x=>x.contentId===c.id),has=M.owned?M.owned(p,c):c.kind==='moves'?!!p.moves[c.id]:p.skills.includes(c.id);return `<article class="merchant-card ${has?'collected':''}"><span class="meta-glyph">${U.icon(d.icon||'star',30)}</span><div class="meta-item-name"><small>${c.kind==='moves'?'招式 · Lv.1':'被動技能'}</small>${label(d)}</div><p>${U.escape(d.description||'可在角色設定查看招式資訊。')}</p>${c.kind==='moves'?`<small class="quiet-note">${U.cost(d)}</small>`:''}<button class="ui-button ${has?'':'primary'}" data-action="shop-buy" data-id="${c.key}" data-epoch="${s.epoch}" ${has||m.marks<c.price?'disabled':''}>${has?'已永久解鎖':`◇ ${c.price} · ${m.marks<c.price?'徽記不足':'解鎖'}`}</button></article>`;}).join('')||'<div class="meta-empty">目前商品池已全部蒐集。<br>攻略更多地下城，解鎖新貨源。</div>'}</div><p class="quiet-note">擊敗敵人、首次發現地下城與通關可累積徽記；整局結束時帶回，失敗也保留。<br>每件商品只需解鎖一次，已有能力不會重複販售。</p>${U.button('配置已學會的能力','setup')}</div>`;
 }
 const tabs=[['moves','招式'],['skills','技能'],['books','魔法書'],['equipment','裝備'],['statuses','狀態'],['monsters','怪物'],['dungeons','地下城']];
 const typeName={moves:'招式',skills:'技能',books:'魔法書',equipment:'裝備',statuses:'狀態',monsters:'生物',dungeons:'遺跡'};
 function codex(game){const all=M.collection(game.permanent),tab=tabs.some(x=>x[0]===game.codexTab)?game.codexTab:'moves',list=all[tab],total=tabs.flatMap(([id])=>all[id]),known=total.filter(x=>x.known).length;
  return `${header('旅途圖鑑','TRACES OF THE UNKNOWN')}<div class="meta-scroll"><div class="meta-banner"><div><small>已發現與蒐集</small><strong>${known} <small>/ ${total.length}</small></strong></div><span>尚有 ${total.length-known} 項未知<br>點選條目查看完整效果</span></div><div class="codex-progress"><i style="width:${100*known/Math.max(1,total.length)}%"></i></div><nav class="codex-tabs codex-all-tabs" aria-label="圖鑑分類">${tabs.map(([id,name])=>`<button data-action="codex-tab" data-id="${id}" class="${tab===id?'selected':''}">${name}<small>${all[id].filter(x=>x.known).length} / ${all[id].length}</small></button>`).join('')}</nav><div class="codex-grid">${list.map((e,i)=>`<button class="codex-entry ${e.known?'known':'unknown'}" data-action="codex-detail" data-id="${e.id}" data-kind="${tab}"><span class="meta-glyph" aria-hidden="true">${e.known?U.icon(e.data.icon||(tab==='monsters'?'hood':tab==='equipment'?'armor':tab==='statuses'?'star':'book'),28):'?'}</span><span><small>No. ${String(i+1).padStart(3,'0')} · ${e.known?tab==='monsters'?(e.complete?'已擊敗':'已遇見'):tab==='dungeons'?(e.complete?'已通關':e.entered?'已進入':'已發現'):'已蒐集':'尚未發現'}</small>${e.known?label(e.data):'<strong>未知的'+typeName[tab]+'</strong>'}<p>${U.escape(e.known?(e.data.description||e.data.features?.join(' ／ ')||'已記錄於旅途圖鑑。'):e.hint)}</p></span></button>`).join('')}</div></div>`;
 }
 const elementName=id=>D.elements[id]||id,modText=m=>{const n={damage:'傷害',incoming:'承受傷害',attackTime:'讀條',agility:'敏捷',accuracy:'命中率',critChance:'爆擊率',dodgeChance:'閃避率','cost:mana':'MP消耗','cost:stamina':'SP消耗',healing:'治療量',chargeRate:'必殺蓄能速度'}[m.stage]||m.stage;return `${m.conditions?.element?elementName(m.conditions.element)+'屬性 ':''}${n}${m.op==='add'?(m.value>=0?'+':'')+m.value:' ×'+m.value}`;};
 const statusText=s=>{const parts=(s.modifiers||[]).map(modText);if(s.tick)parts.push(`每 ${s.tick.interval} 秒造成施放者最大${s.tick.stat==='mana'?'MP':s.tick.stat==='stamina'?'SP':'HP'}的 ${Math.round(s.tick.ratio*1000)/10}% 傷害`);if(s.consume)parts.push(`下一次${s.consume==='physical'?'物理':'魔法'}招式後消失`);return parts.join('；')||'狀態標記，重複施加時刷新持續時間';};
 const effectText=m=>(m.effects||[]).map(e=>e.type==='interrupt'?'中斷敵人目前讀條':e.type==='heal'?`恢復最大 HP ${e.ratio*100}%`:e.type==='restore'?`恢復 ${e.amount} ${e.resource==='mana'?'MP':'SP'}`:e.type==='shield'?`獲得最大 HP ${e.ratio*100}% 的護盾`:e.type==='cleanse'?'移除戰鬥 Debuff':e.status?`${e.status.name}（${e.status.duration}秒）：${statusText(e.status)}`:e.type).join('；')||'無額外狀態效果';
 function codexDetail(game,kind,id){const all=M.collection(game.permanent),entry=all[kind]?.find(x=>x.id===id);if(!entry)return '<h2 id="modal-title">找不到圖鑑資料</h2>';if(!entry.known)return `<div class="eyebrow">UNKNOWN ${typeName[kind].toUpperCase()}</div><h2 id="modal-title">尚未發現</h2><p>${U.escape(entry.hint)}</p><div class="modal-footer">${U.button('返回圖鑑','close')}</div>`;const d=entry.data;let body='';
  if(kind==='moves'){const lv=game.permanent.moves[id]||1;body=U.moveDetail(d,lv,0,true)+`<p class="effect-note"><b>完整效果：</b>${U.escape(effectText(d))}</p>`;}
  else if(kind==='skills'){const mechanics=[...(d.combatModifiers||[]).map(modText),...(d.hooks||[]).map(h=>`${h.event} 時觸發`),...Object.entries(d.modifiers||{}).map(([k,v])=>`${k.toUpperCase()} +${v}`),...Object.entries(d.statRates||{}).map(([k,v])=>`${k.toUpperCase()} +${v*100}%`)];body=`<div class="eyebrow">PASSIVE SKILL · ${U.gradeBadge(d)}</div><h2 id="modal-title">${U.escape(d.name)}</h2><p>${U.escape(d.description)}</p><p class="effect-note"><b>實際效果：</b>${U.escape(mechanics.join('；')||'效果已由專屬觸發器執行')}</p>`;}
  else if(kind==='books'){const learned=!!game.permanent.moves[d.moveId],req=game.permanent.moves[d.requirement.moveId]||0;body=`<div class="eyebrow">MAGIC GRIMOIRE</div><h2 id="modal-title">《${U.escape(d.name)}》</h2><p>${U.escape(d.description)}</p><p>理解條件：${U.escape(D.moves[d.requirement.moveId].name)} 永久 Lv.${d.requirement.level}（目前 Lv.${req}）</p><p>學會招式：${U.escape(D.moves[d.moveId].name)} · ${learned?'已理解':'尚未理解'}</p>`;}
  else if(kind==='equipment'){body=`<div class="eyebrow">${U.escape(D.equipmentRarityLabels?.[d.rarity]||'普通')} EQUIPMENT · ${U.gradeBadge(d)}</div><h2 id="modal-title">${U.escape(d.name)}</h2><p>${U.escape(d.description)}</p><p>部位：${U.escape(({head:'頭部',chest:'身體',arms:'手部',feet:'腳部',weapon:'武器'})[d.slot])}${d.weaponType?' · 類型：'+U.escape(({sword:'劍',bow:'弓',blunt:'鈍器',staff:'法杖'})[d.weaponType]):''}</p>`;}
  else if(kind==='statuses'){body=`<div class="eyebrow">${d.polarity==='buff'?'BUFF':'DEBUFF'}</div><h2 id="modal-title">${U.escape(d.name)}</h2><p>持續 ${d.duration} 秒</p><p class="effect-note">${U.escape(statusText(d))}</p><p>${U.escape(d.description)}</p>`;}
  else if(kind==='monsters'){body=`<div class="eyebrow">BESTIARY</div><h2 id="modal-title">${U.escape(d.name)}</h2><p>屬性：${(d.elements||[]).map(elementName).join('＋')||'無'} · 行動：${U.escape(d.behavior||'未知')}</p><p>招式：${(d.moves||[]).map(x=>D.moves[x]?.name).filter(Boolean).map(U.escape).join('、')}</p>`;}
  else body=`<div class="eyebrow">DUNGEON RECORD</div><h2 id="modal-title">${U.escape(d.name)}</h2><p>建議 Lv.${d.recommendedLevel||d.level} · ${U.escape(d.description)}</p><p>特色：${(d.features||[]).map(U.escape).join('／')}</p>`;
  return `${body}<div class="modal-footer">${U.button('返回圖鑑','close')}</div>`;
 }
 function settlement(run){const r=M.ledger(run);return `<section class="meta-settlement"><small>本局帶回 · 旅者徽記</small><strong>＋${r.total} ◇</strong><p>戰鬥 ${r.combat} · 探索 ${r.exploration} · 地下城 ${r.dungeons}</p><small>已存入局外商店錢包</small></section>`;}
 root.MetaScreens={shop,codex,codexDetail,settlement};
})(globalThis);
