const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const D=require('./data'),P=require('./progression'),Save=require('./run-save');
function game(){const permanent=P.freshProgress(),run=P.createRun(permanent);return {permanent,run,build:run.build,scene:'explore',battle:null,modal:null};}
function memory(){const m=new Map();return {getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)};}
test('戰鬥快照保留資源、讀條、狀態與一次性技能；恢復後結算一致',()=>{const g=game(),store=memory();g.scene='battle';g.encounter={type:'greywind_elite',level:4};g.battle=P.battleFor(g.run,g.encounter,()=>.99);g.battle.choose('fire');g.battle.advance(.75);g.battle.enemy.runtime.once.add('unyielding:OnInterruptReceived');Save.save(store,g);const restored=Save.load(store);assert.equal(restored.warning,undefined);const b=restored.snapshot.battle;b.rng=()=>.99;assert.deepEqual(b.player.cast,g.battle.player.cast);assert.equal(b.charge,g.battle.charge);assert.ok(b.enemy.runtime.once.has('unyielding:OnInterruptReceived'));g.battle.advance(2);b.advance(2);assert.equal(b.player.hp,g.battle.player.hp);assert.equal(b.enemy.hp,g.battle.enemy.hp);assert.equal(b.time,g.battle.time);});
test('毀損／版本不符及儲存拒絕有明確失敗；測試戰鬥不覆寫本局',()=>{const s=memory(),g=game();assert.equal(Save.save(s,g),true);const raw=s.getItem(Save.KEY);g.debugBattle=true;g.run.level=99;Save.save(s,g);assert.equal(s.getItem(Save.KEY),raw);s.setItem(Save.KEY,'{');assert.ok(Save.load(s).warning);s.setItem(Save.KEY,JSON.stringify({version:99}));assert.ok(Save.load(s).warning);assert.equal(Save.save({setItem(){throw Error('quota');}},game()),false);});
function worker(fail=false){const events={},stores=new Map(),scope='https://example.test/game/',calls=[];const caches={open:async key=>{if(!stores.has(key))stores.set(key,new Map());const map=stores.get(key);return {addAll:async assets=>{if(fail)throw Error('offline');for(const a of assets)map.set(new URL(a,scope).href,'cached:'+a);},match:async key=>map.get(key)};},keys:async()=>[...stores.keys()],delete:async key=>stores.delete(key)};const self={registration:{scope},clients:{claim:async()=>calls.push('claim')},addEventListener:(k,v)=>events[k]=v};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'sw.js'),'utf8'),{self,caches,URL,fetch:async()=>{throw Error('network disabled');}});return {events,stores,calls,scope,dispatch:async kind=>{let p;events[kind]({waitUntil:x=>p=x});await p;}};}
test('Service Worker 完整安裝後，斷網重整根目錄／PLAY／index 與資源皆由快取供應',async()=>{const w=worker();await w.dispatch('install');await w.dispatch('activate');assert.deepEqual(w.calls,['claim']);for(const file of ['','PLAY.html','index.html','app.js','run-save.js','icon-192.png']){let result;w.events.fetch({request:{url:w.scope+file+'?reload=1',method:'GET'},respondWith:p=>result=p});assert.match(await result,/^cached:/);}let used=false;w.events.fetch({request:{url:'https://other.test/app.js',method:'GET'},respondWith:()=>used=true});assert.equal(used,false);});
test('離線下載不完整不可啟用，舊版與其他網站快取保留',async()=>{const w=worker(true);w.stores.set('other-game',new Map());await assert.rejects(w.dispatch('install'));assert.equal(w.stores.size,1);assert.ok(w.stores.has('other-game'));});
test('PWA 套件每個預快取檔案存在，manifest 使用相對路徑支援子目錄',()=>{const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'manifest.webmanifest')));assert.equal(manifest.start_url,'./PLAY.html');assert.equal(manifest.display,'standalone');assert.equal(manifest.orientation,'portrait');assert.ok(manifest.display_override.includes('standalone'));const source=fs.readFileSync(path.join(__dirname,'sw.js'),'utf8'),assets=JSON.parse(source.match(/ASSETS=(\[[^;]+\])/)[1]);for(const file of assets.filter(x=>x!=='./'))assert.ok(fs.existsSync(path.join(__dirname,file)));for(const icon of manifest.icons)assert.ok(fs.existsSync(path.join(__dirname,icon.src)));assert.ok(assets.includes('./pwa-install.js'));});
test('手機 PWA 安裝介面包含 Android 安裝提示、iOS 主畫面指引與直式鎖定嘗試',()=>{const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),script=fs.readFileSync(path.join(__dirname,'pwa-install.js'),'utf8');for(const value of ['apple-mobile-web-app-capable','apple-mobile-web-app-status-bar-style','apple-mobile-web-app-title','pwa-install'])assert.ok(html.includes(value));for(const value of ['beforeinstallprompt','appinstalled','Safari 點「分享」','orientation.lock(\'portrait\')'])assert.ok(script.includes(value));});
