const test=require('node:test'),assert=require('node:assert/strict');
const P=require('./progression'),Save=require('./run-save');
function fixture(){const p=P.freshProgress();p.ultimateUnlocked=true;const run=P.createRun(p,{...P.defaultBuild(),ultimate:'nova'});return {p,run};}
test('全局收穫分類合併、記錄新解鎖及重複取得，初始收藏不算收穫',()=>{const {p,run}=fixture();assert.deepEqual(run.loot,{});P.grantRewards(p,run,[{kind:'moves',id:'fire'},{kind:'moves',id:'spark'},{kind:'talents',id:'economy'},{kind:'equipment',id:'windboots'},{kind:'books',id:'inferno'}]);P.grantRewards(p,run,[{kind:'moves',id:'fire'},{kind:'talents',id:'economy'},{kind:'equipment',id:'windboots'}]);assert.equal(Object.keys(run.loot).length,5);assert.equal(run.loot['moves:fire'].count,2);assert.equal(run.loot['moves:fire'].before,1);assert.equal(run.loot['moves:fire'].after,3);assert.equal(run.loot['moves:fire'].isNew,false);assert.equal(run.loot['moves:spark'].isNew,true);assert.equal(run.loot['talents:economy'].count,2);assert.equal(run.loot['equipment:windboots'].count,2);assert.equal(run.loot['books:inferno'].count,1);P.resolveAcquisition(run,'moves','spark');assert.equal(run.loot['moves:spark'].count,1);});
test('地下城重複領獎被拒絕，收穫不重記；新局清空清單',()=>{const {p,run}=fixture();run.dungeon={id:'abandoned_mine',stage:3};P.dungeonReward(p,run,()=>0);const before=JSON.stringify(run.loot);P.dungeonReward(p,run,()=>0);assert.equal(JSON.stringify(run.loot),before);assert.deepEqual(P.createRun(p).loot,{});});
test('大絕部分／滿格充能跨野外及地下城保留，施放扣回零再累積',()=>{const {run}=fixture(),cost=P.ultimateChargeCost(run);let b=P.battleFor(run,{type:'greywind_0',level:2});b.charge=7.25;P.carryBattleCharge(run,b);b=P.battleFor(run,{type:'greywind_0',level:2});assert.equal(b.charge,7.25);b.charge=cost;P.carryBattleCharge(run,b);run.dungeon={id:'abandoned_mine',stage:0};b=P.battleFor(run,P.dungeonEncounter(run));assert.equal(b.charge,cost);assert.equal(b.choose('nova').ok,true);assert.equal(b.charge,0);b.advance(.5);P.carryBattleCharge(run,b);assert.equal(P.battleFor(run,P.dungeonEncounter(run)).charge,.5);assert.equal(P.createRun(P.freshProgress()).ultimateCharge,0);});
test('資源不足不吃充能、死亡仍保留、異常超值限制於上限',()=>{const {run}=fixture(),cost=P.ultimateChargeCost(run);const b=P.battleFor(run,{type:'greywind_0',level:2});b.charge=cost;b.player.mana=0;assert.equal(b.choose('nova').ok,false);assert.equal(b.charge,cost);b.finish(false);P.carryBattleCharge(run,b);assert.equal(run.ultimateCharge,cost);run.ultimateCharge=500;run.ultimateChargeVersion=2;assert.equal(P.battleFor(run,{type:'greywind_0',level:2}).charge,cost);});
test('收穫與場外充能可存檔接續；舊存檔標記不完整歷史',()=>{const {p,run}=fixture();P.grantRewards(p,run,[{kind:'books',id:'inferno'}]);run.ultimateCharge=9;let raw;const store={setItem:(k,v)=>raw=v,getItem:()=>raw};Save.save(store,{scene:'explore',run,permanent:p,build:run.build});let loaded=Save.load(store).snapshot;assert.equal(loaded.run.ultimateCharge,9);assert.equal(loaded.run.loot['books:inferno'].count,1);const old=JSON.parse(raw);delete old.run.loot;delete old.run.ultimateCharge;raw=JSON.stringify(old);loaded=Save.load(store).snapshot;assert.equal(loaded.run.lootHistoryPartial,true);assert.equal(loaded.run.ultimateCharge,0);});
test('每個招式有獨立必殺蓄能需求，普通招式也可指定為必殺',()=>{const {p,run}=fixture();for(const move of Object.values(require('./data').moves))assert.ok(Number.isFinite(move.ultimateChargeCost)&&move.ultimateChargeCost>=60&&move.ultimateChargeCost<=200);assert.equal(require('./data').moves.quick.ultimateChargeCost,65);assert.equal(require('./data').moves.fire.ultimateChargeCost,90);run.build.ultimate='fire';P.validateBuild(run.build,p);let b=P.battleFor(run,{type:'greywind_0',level:2});assert.equal(b.choose('fire').ok,true,'普通欄位不應需要必殺蓄能');assert.equal(b.charge,0);b=P.battleFor(run,{type:'greywind_0',level:2});b.charge=89;assert.equal(b.choose('fire',true).ok,false);b.charge=90;assert.equal(b.choose('fire',true).ok,true);assert.equal(b.charge,0);});
