/* Atomic run + collection snapshot; executable runtime objects are rebuilt on load. */
(function(root){
 const D=typeof module!=='undefined'?require('./data.js'):root.GameData;
 const P=typeof module!=='undefined'?require('./progression.js'):root.Progression;
 const KEY='afterlight.session.v1',copy=x=>JSON.parse(JSON.stringify(x));
 const fields=['scene','run','permanent','build','encounter','result','resultDelay','resultHandled','rewards','fieldRewards','offered','noRandom'];
 function pack(game){const out={version:1,worldVersion:D.worldContentVersion,savedAt:Date.now()};for(const k of fields)if(game[k]!==undefined)out[k]=copy(game[k]);out.modal=['result','reward','acquire','replace','replace-confirm'].includes(game.modal)?game.modal:null;
 if(game.battle){const b=game.battle;out.battle={};for(const k of ['time','phase','charge','enemyTurn','run'])out.battle[k]=copy(b[k]);if(b.lastOutcome)out.battle.lastOutcome=copy(b.lastOutcome);for(const id of ['player','enemy']){const {runtime,...actor}=b[id];out.battle[id]={...copy(actor),once:[...runtime.once]};}}
 return out;}
 function save(storage,game){if(game.debugBattle)return true;try{storage.setItem(KEY,JSON.stringify(game.run?pack(game):{version:1,run:null,permanent:game.permanent}));return true;}catch(_){return false;}}
 function load(storage){try{const raw=storage.getItem(KEY);if(!raw)return {snapshot:null};const s=JSON.parse(raw);if(s.version!==1)throw Error('存檔版本不相容');if(!s.run)return {snapshot:null};if(s.worldVersion!==D.worldContentVersion)throw Error('世界版本不相容');
 const run=s.run;run.defeatedEnemyTypesThisRun=[...new Set((run.defeatedEnemyTypesThisRun||[]).filter(id=>D.monsters[id]))];if(!run.battleStats)run.battleStatsPartial=true; if(s.permanent.ultimateUnlocked===undefined)s.permanent.ultimateUnlocked=run.status==='failed';if(!s.permanent.ultimateUnlocked){run.build.ultimate=null;if(s.build)s.build.ultimate=null;}run.points=0;if(!run.loot){run.loot={};run.lootHistoryPartial=true;}if(!Number.isFinite(run.ultimateCharge))run.ultimateCharge=0;P.validateBuild(run.build,s.permanent);P.normalizeUltimateCharge(run);P.statsFor(run);if(!Number.isInteger(run.level)||run.level<1||!['active','failed'].includes(run.status)||!Number.isFinite(run.position.x)||!Number.isFinite(run.position.y)||!Array.isArray(run.world.enemies))throw Error('冒險資料不完整');for(const e of run.world.enemies)if(!D.monsters[e.type]||!Number.isFinite(e.level))throw Error('敵人資料不相容');if(run.dungeon)P.dungeonEncounter(run);
 if(!['explore','battle'].includes(s.scene))throw Error('場景不相容');if(s.scene==='battle'){if(!s.battle||!D.monsters[s.encounter?.type])throw Error('戰鬥資料不完整');const b=P.battleFor(run,s.encounter);for(const k of ['time','phase','charge','enemyTurn','run'])b[k]=s.battle[k];b.lastOutcome=s.battle.lastOutcome;if(!Number.isFinite(b.time)||!['fighting','victory','revived','gameover'].includes(b.phase))throw Error('戰鬥狀態不相容');for(const id of ['player','enemy']){const actor=s.battle[id],runtime=b[id].runtime;if(!actor||!Number.isFinite(actor.hp)||!Number.isFinite(actor.mana)||!Number.isFinite(actor.stamina))throw Error('資源資料不完整');if(actor.cast&&(!D.moves[actor.cast.moveId]||!Number.isFinite(actor.cast.endAt)||actor.cast.endAt<b.time))throw Error('讀條不相容');for(const status of Object.values(actor.statuses||{}))if(!Number.isFinite(status.expiresAt)||status.tick&&(!(status.tick.interval>0)||!Number.isFinite(status.nextTick)))throw Error('狀態不相容');const {once,...data}=actor;Object.assign(b[id],data);runtime.once=new Set(once||[]);}b.events=[];if(s.noRandom){b.rules.critChance=0;b.rules.dodgeChance=0;}s.battle=b;}
 P.ensureWorldContent(run);return {snapshot:s};}catch(error){return {snapshot:null,warning:'無法接續冒險：'+error.message+'。永久收藏仍保留。'};}}
 const api={KEY,pack,save,load};if(typeof module!=='undefined')module.exports=api;else root.RunSave=api;
})(globalThis);
