/* Screen templates composed from the shared UI kit. Actions are handled by app.js. */
(function (root) {
  const D = root.GameData, P = root.Progression, U = root.GameUI;
  const names = { hp: '血量', stamina: '體力', mana: '魔力', agility: '敏捷', luck: '運氣' };
  const symbols = { hp: 'heart', stamina: 'sword', mana: 'orb', agility: 'wind', luck: 'star' };
  const slots = { head: '頭部', chest: '胸部', arms: '手部', feet: '腳部', weapon: '武器' };
  const header = (title, subtitle, extra = '') => `<header class="screen-header"><div><div class="eyebrow">${subtitle}</div><h1>${title}</h1></div>${extra}${U.button('返回 <kbd>Esc</kbd>', 'screen-back')}</header>`;
  const footer = (text, actions) => `<footer class="screen-footer"><span>${text}</span><div>${actions}</div></footer>`;
  const sortOptions=[['rarity','稀有度'],['type','類型'],['element','屬性'],['name','名稱']];
  function sortControls(game){const key=game.contentSort||'rarity';return `<nav class="content-sort" aria-label="排列方式"><span>排列</span>${sortOptions.map(([id,label])=>`<button data-action="content-sort" data-id="${id}" aria-pressed="${key===id}" class="${key===id?'selected':''}">${label}</button>`).join('')}<button data-action="content-sort-direction" aria-label="切換排列順序">${key==='rarity'?(game.contentSortReverse?'低→高':'高→低'):(game.contentSortReverse?'反向':'正序')}</button></nav>`;}
  function sortIds(game,ids,kind){const registry=kind==='talents'?D.skills:kind==='equipment'?D.equipment:kind==='books'?D.books:D.moves,key=game.contentSort||'rarity',compare=(a,b)=>String(a||'').localeCompare(String(b||''),'zh-Hant'),data=id=>{const x=registry[id];return kind==='books'?{...D.moves[x.moveId],name:x.name,localizedName:x.name,subtitle:''}:x;},grade=x=>({C:1,B:2,A:3,S:4,SS:5}[x.powerGrade]||{common:1,uncommon:2,rare:3,legendary:4}[x.rarity]||1),type=x=>x.specKind||x.damageType||x.weaponType||x.skillCategory||x.category||x.slot||'',elements=x=>(x.targetElements||x.elements||[]).map(e=>D.elements[e]||e).join('＋');return [...new Set(ids)].filter(id=>registry[id]).sort((a,b)=>{const x=data(a),y=data(b),rarity=grade(y)-grade(x),types=compare(type(x),type(y)),name=compare(x.localizedName||x.subtitle||x.name,y.localizedName||y.subtitle||y.name);let result=key==='rarity'?rarity||types:key==='type'?types||rarity:key==='element'?compare(elements(x),elements(y))||types||rarity:name;result=result||name||compare(a,b);return game.contentSortReverse?-result:result;});}
  function setup(game, tab = 'stats') {
    const run = P.createRun(game.permanent, game.build, () => .5), stats = P.statsFor(run), detail = P.statBreakdown(run),cls=root.ClassSystem.active(run);
    let body;
    if (tab === 'stats') body = `<div class="section-heading"><h2>旅人的素質</h2><small>LV. 01 · 目前開局數值</small></div><div class="stat-cards">${Object.keys(names).map(k => `<button class="stat-card stat-${k}" data-action="stat-explain" data-id="${k}" data-tooltip="stat:${k}"><span class="stat-glyph">${U.icon(symbols[k], 31)}</span><span class="stat-name">${names[k]}<small>基礎數值</small></span><strong>${Math.round(stats[k])}</strong><span class="growth">成長 <b>+${Math.round(detail[k].bonusRate * 100)}%</b><i style="--fill:${Math.min(100, 30 + detail[k].bonusRate * 100)}%"></i></span></button>`).join('')}</div><p class="quiet-note"><strong>${U.escape(cls.innateTrait.name)}</strong>：${U.escape(cls.innateTrait.description)}</p><p class="quiet-note">${U.escape(cls.className)}職業倍率：${Object.keys(names).map(k=>`${names[k]} ×${cls.baseStatMultipliers[k]}／成長 ×${cls.levelGrowthMultipliers[k]}`).join(" · ")}。</p><p class="quiet-note">升級自動提升五項能力；技能可再強化成長。點按數值查看明細。</p>`;
    else if (tab === 'build') body = `<div class="section-heading"><h2>【技能】</h2><small>被動能力 · ${game.build.talents.length} / 4</small></div><div class="loadout-row">${Array.from({ length: 4 }, (_, i) => U.slot(game.build.talents[i], 'talents', i)).join('')}</div><div class="section-heading"><h2>［普通招式］</h2><small>上 → 右 → 下 → 左 · ${game.build.moves.length} / 4</small></div><div class="loadout-row">${Array.from({ length: 4 }, (_, i) => U.slot(game.build.moves[i], 'moves', i, 'slot-pick', game.permanent.moves[game.build.moves[i]] || 1)).join('')}</div><div class="ultimate-loadout">${U.slot(game.build.ultimate, 'ultimate', 0)}<div><small class="eyebrow">YOUR FINAL LIGHT</small><h3>［必殺技］</h3><p>${game.build.ultimate ? `必殺蓄能：${U.ultimateChargeSpeed(game.build.ultimate)}<br>` : ''}任何已學會招式都可指定為必殺技。<br>充滿後仍需支付資源。</p></div></div>`;
    else body = `<div class="section-heading"><h2>旅人的行裝</h2><small>五個欄位 · 點選更換</small></div><div class="paperdoll">${U.characterArt()}${Object.entries(slots).map(([slot, name]) => `<div class="gear-position gear-${slot}"><small>${name}</small>${U.slot(game.build.equipment[slot], 'equipment', slot, 'gear-pick')}</div>`).join('')}</div>`;
    return `<div class="polished-page loadout-page">${header('角色設定', 'THE TRAVELLER · LOADOUT')}<div class="setup-layout"><aside class="character-column"><div class="character-caption"><span>目前職業</span><h2>${U.escape(cls.className)}</h2></div><div class="character-display">${U.characterArt()}</div><div class="character-footer"><span>「沒有預言指引，只有前路。」</span><div><b>4</b> 技能上限 <i>／</i> <b>4</b> 招式上限 <i>／</i> <b>1</b> 必殺技</div></div></aside><section class="setup-content">${U.tabs([['stats', '能力'], ['build', '配置'], ['equipment', '裝備']], tab, 'setup-tab')}<div class="setup-tab-content">${body}</div></section></div>${footer('配置會保留至下次出發。永久收藏不會因本局死亡而失去。', U.button('搭配預設', 'presets') + U.button('選擇職業', 'class-achievements') + U.button('能力庫存', 'library') + U.button('開始冒險 <span>→</span>', 'begin-run', { primary: true, disabled: !game.build.moves.length }))}</div>`;
  }
  function library(game, category, selected) {
    const rawIds = category === 'talents' ? game.permanent.skills : category === 'books' ? game.permanent.books : [...Object.keys(game.permanent.moves), ...game.permanent.ultimates];
    const ids=sortIds(game,rawIds,category);
    const id = ids.includes(selected) ? selected : ids[0]; let details = '<div class="empty-detail">' + U.icon('book', 80) + '<h3>尚未發現的知識</h3><p>探索各地地下城，收集魔法書。<br>每一頁，都將留到下一段旅途。</p></div>';
    if (id && category === 'moves') {
      const move = D.moves[id], level = game.permanent.moves[id] || 1, view = { ...move, multiplier: move.multiplier * P.moveScale(level) };
      const equipped = move.kind === 'ultimate' ? game.build.ultimate === id : game.build.moves.includes(id);
      details = U.moveDetail(view, level, P.statsFor(P.createRun(game.permanent, game.build)).agility, true) + U.button(equipped ? '從開局 Build 移除' : '加入開局 Build', 'library-equip', { id, primary: !equipped });
    } else if (id && category === 'talents') { const skill = D.skills[id], equipped = game.build.talents.includes(id); details = `<div class="detail-icon tone-${U.tone(id)}">${U.icon(skill.icon, 72)}</div><small class="eyebrow">PASSIVE ABILITY · ${U.gradeBadge(skill)}</small><h3>${skill.name}</h3><span class="detail-badge">已學會 · Lv.1</span><p>${skill.description}</p><p>分類：${skill.category}</p><p class="effect-note">只要配置於技能欄，效果就會自動生效。</p>${U.button(equipped ? '從開局 Build 移除' : '加入開局 Build', 'library-equip', { id, primary: !equipped })}`; }
    else if (id) { const book = D.books[id], current = game.permanent.moves[book.requirement.moveId] || 0, learned = !!game.permanent.moves[book.moveId]; details = `<div class="detail-icon tone-violet">${U.icon('book', 72)}</div><small class="eyebrow">PERMANENT KNOWLEDGE</small><h3>《${book.name}》</h3><span class="detail-badge">${learned ? '已理解' : '尚未理解'}</span><p>${book.description}</p><div class="book-condition"><small>學習條件</small><strong>${D.moves[book.requirement.moveId].name} · 永久 Lv.${book.requirement.level}</strong>${U.stars(current)}<span>${current} / ${book.requirement.level}</span><div class="condition-track"><i style="width:${Math.min(100, current / book.requirement.level * 100)}%"></i></div></div>${U.button(learned ? '已學會'+D.moves[book.moveId].name : '理解 · 學習魔法', 'learn-book', { id, primary: true, disabled: learned || current < book.requirement.level })}`; }
    return `${header('能力庫存', 'THE ARCHIVE · PERMANENT COLLECTION', '<span class="permanent-mark">◇ 局外永久收藏</span>')}<div class="library-layout"><nav class="library-nav" aria-label="能力分類">${[['talents', '技能', 'wind'], ['moves', '招式', 'sword'], ['books', '魔法書', 'book']].map(([key, name, icon]) => `<button class="${category === key ? 'selected' : ''}" data-action="library-category" data-id="${key}">${U.icon(icon, 25)}<span>${name}</span><b>${key === 'talents' ? game.permanent.skills.length : key === 'moves' ? Object.keys(game.permanent.moves).length + game.permanent.ultimates.length : game.permanent.books.length}</b></button>`).join('')}<p>知識會留下。<br>每段旅途，都從這裡重新出發。</p></nav><section class="library-center"><div class="section-heading"><h2>${category === 'talents' ? '已學會的技能' : category === 'moves' ? '記憶中的招式' : '收藏的魔法書'}</h2><small>${ids.length} 項收藏</small></div>${sortControls(game)}<div class="catalog-grid">${ids.map(key => U.card(key, category, game.permanent.moves[key] || 1, key === id)).join('') || '<div class="empty-catalog">' + U.icon('book', 64) + '<p>第一本魔法書，仍在遺跡中等待。</p></div>'}</div><p class="quiet-note">★ 代表永久熟練度，最高 3 級。局內等級獨立成長。</p></section><aside class="ability-detail">${details}</aside></div>${footer('這是出發前的能力庫。冒險中僅在取得新能力時可選擇裝備。', U.button('前往角色設定', 'setup') + U.button('開始冒險 →', 'begin-run', { primary: true, disabled: !game.build.moves.length }))}`;
  }
  function settings(settings) {
   const toggle=(id,title,description)=>`<div class="setting-row"><div><h3>${title}</h3><p>${description}</p></div><button class="toggle ${settings[id]?'selected':''}" data-action="setting-toggle" data-id="${id}" aria-label="${title}" aria-pressed="${!!settings[id]}">${settings[id]?'開啟':'關閉'}</button></div>`;
   return `<div class="polished-page settings-page">${header('設定','PREFERENCES')}<div class="preferences-version"><span>遊戲版本</span><strong>v${U.escape(D.release.version)}</strong><small>${U.escape(D.release.date)}</small></div><section class="preference-group"><h2>冒險</h2>${toggle('autoQuickBattle','自動壓制低等野怪',`本局已正常擊敗的普通野怪，領先 ${D.balance.quickBattleLevelGap} 級時自動結算。菁英、Boss 與地下城除外。`)}<div class="setting-row"><div><h3>沉浸式全螢幕</h3><p>以直式畫面專注探索。</p></div>${U.button('切換','fullscreen')}</div></section><section class="preference-group"><h2>聲音與畫面</h2>${toggle('sound','介面與戰鬥音效','保留攻擊、收穫與升級的聲音回饋。')}<label class="setting-row"><div><h3>音效音量</h3><p id="volume-label">${Math.round(settings.volume*100)}%</p></div><input type="range" id="volume" aria-label="音效音量" min="0" max="100" value="${Math.round(settings.volume*100)}"></label>${toggle('reducedMotion','減少動態效果','減少場景粒子與鏡頭震動；升級跳字與閃光保留。')}${toggle('contrast','提高介面對比','讓文字與重要資訊更容易辨識。')}</section><section class="preference-group"><h2>存檔與離線</h2><div class="setting-row"><div><h3>自動保存旅程</h3><p id="offline-detail">${U.escape(root.GameOffline?.status||'正在確認離線狀態。')}</p><p>重整後可接續冒險。清除網站資料會刪除收藏與存檔。</p></div></div></section><details class="utility-section"><summary>操作說明與進階選項</summary><div class="control-reference"><span>移動 <b>W A S D</b></span><span>招式 <b>W A S D／方向鍵</b></span><span>必殺 <b>Space</b></span></div><div class="utility-actions">${U.button('世界測試','world-debug')}${U.button('戰鬥測試','debug-lab')}${U.button('基礎配置重新出發','restart-basic')}${U.button('完全重置','full-reset')}</div></details>${footer('設定自動保存於目前瀏覽器。',U.button('返回','screen-back',{primary:true}))}</div>`;
  }
  function picker(game, kind, index) {
    if(kind==='ultimate'&&game.permanent.ultimateUnlocked===false)return `<h2 id="modal-title">必殺槽尚未解鎖</h2><p>首次冒險第三次倒下、完成整局結算後永久解鎖。</p><div class="modal-footer">${U.button('返回','close')}</div>`;
    const rawIds = kind === 'talents' ? game.permanent.skills : kind === 'ultimate' ? [...new Set([...Object.keys(game.permanent.moves), ...game.permanent.ultimates])] : kind === 'equipment' ? game.permanent.equipment.filter(id => D.equipment[id].slot === index) : Object.keys(game.permanent.moves);
    const ids=sortIds(game,rawIds,kind);
    const current = kind === 'ultimate' ? game.build.ultimate : kind === 'equipment' ? game.build.equipment[index] : game.build[kind][index];
    return `<div class="eyebrow">CHOOSE YOUR PATH</div><h2 id="modal-title">${kind === 'equipment' ? '選擇' + slots[index] + '裝備' : kind === 'talents' ? '選擇技能' : kind === 'ultimate' ? '選擇必殺技' : '選擇招式'}</h2>${sortControls(game)}<div class="picker-grid">${ids.map(id => { const data = kind === 'talents' ? D.skills[id] : kind === 'equipment' ? D.equipment[id] : D.moves[id]; const used = ['moves', 'talents'].includes(kind) && game.build[kind].includes(id) && current !== id, rarity=kind==='equipment'?(D.equipmentRarityLabels?.[data.rarity]||'普通'):null, sources=kind==='equipment'?(data.acquisitionTier==='easy'?'容易取得':(data.sourceDungeons||[]).map(dungeonId=>D.dungeons.find(d=>d.id===dungeonId)?.name).filter(Boolean).join('／')||'特殊取得'):null; return `<button class="picker-card tone-${U.tone(id)} ${current === id ? 'selected' : ''}" data-action="picker-select" data-id="${id}" ${kind==='talents'?`data-tooltip="skill:${id}"`:""} ${used ? 'disabled' : ''}>${U.icon(data.icon, 35)}<div><strong>${data.name} ${U.gradeBadge(data)}</strong><p>${kind==='ultimate' ? `必殺蓄能：${U.ultimateChargeSpeed(id)} · ` : kind==='talents'?data.category+" · ":""}${data.description}</p>${kind==='equipment'?`<small class="gear-rarity rarity-${data.rarity}">${rarity} · ${sources}</small>`:''}<small>${used ? '已在其他欄位' : kind === 'moves' ? `永久 Lv.${game.permanent.moves[id]}` : current === id ? '目前配置' : '可以配置'}</small></div></button>`; }).join('')}</div><div class="modal-footer">${current ? U.button('卸下此欄位', 'picker-remove') : ''}${U.button('取消', 'close')}</div>`;
  }
  root.GameScreens = { sortIds,sortControls,setup, library, settings, picker, statNames: names, statIcons: symbols };
})(globalThis);
