/* Shared presentation primitives. No combat formula or mutable run state lives here. */
(function (root) {
  const D = root.GameData, P = root.Progression, art = root.GameArt;
  const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const tone = id => ['fire', 'inferno'].includes(id) ? 'ember' : ['spark', 'control'].includes(id) ? 'arcane' : ['nova', 'lucky'].includes(id) ? 'gold' : ['interrupt'].includes(id) ? 'violet' : 'jade';
  const stars = level => `<span class="stars" aria-label="永久熟練度 ${level} 級">${'★'.repeat(Math.min(3, level))}<span>${'☆'.repeat(Math.max(0, 3 - level))}</span></span>`;
  const icon = (name, size = 32) => art.icon(name, size);
  const button = (text, action, options = {}) => `<button class="${options.primary ? 'primary-button' : 'secondary-button'} ${options.className || ''}" data-action="${action}" ${options.id ? `data-id="${options.id}"` : ''} ${options.disabled ? 'disabled' : ''}>${text}</button>`;
  const tabs = (items, active, action) => `<nav class="tabs" aria-label="畫面分頁">${items.map(([id, text]) => `<button class="tab-button ${active === id ? 'selected' : ''}" data-action="${action}" data-id="${id}" aria-pressed="${active === id}">${text}</button>`).join('')}</nav>`;
  function card(id, kind, level, selected = false, action = 'catalog-select') {
    const data = kind === 'talents' ? D.skills[id] : kind === 'books' ? D.books[id] : kind === 'equipment' ? D.equipment[id] : D.moves[id];
    return `<button class="ability-card tone-${tone(id)} ${selected ? 'selected' : ''}" data-action="${action}" data-id="${id}" data-kind="${kind}" aria-pressed="${selected}"><span class="card-seal">${icon(data.icon || 'book', 43)}</span><strong>${data.name}</strong>${kind==='talents'?`<small class="skill-card-category">${escape(data.description)}</small>`:''}${kind === 'moves' && data.kind !== 'ultimate' ? stars(level) : `<small>${kind === 'books' ? '永久知識' : data.kind === 'ultimate' ? '必殺技' : kind === 'equipment' ? '旅人裝備' : data.category + ' · Lv.1'}</small>`}</button>`;
  }
  function slot(id, kind, index, action = 'slot-pick', level = 1) {
    const data = kind === 'talents' ? D.skills[id] : kind === 'equipment' ? D.equipment[id] : D.moves[id];
    return `<button class="loadout-slot tone-${tone(id)} ${id ? 'filled' : 'empty'} ${kind === 'ultimate' ? 'ultimate-slot' : ''}" data-action="${action}" data-kind="${kind}" data-index="${index}" data-id="${id || ''}"><span class="slot-frame">${id ? icon(data.icon, kind === 'ultimate' ? 45 : 35) : '<span class="plus">＋</span>'}</span><strong>${data?.name || '空欄位'}</strong><small>${id ? kind === 'talents' ? '被動 · Lv.1' : kind === 'equipment' ? data.description : `永久 Lv.${level}` : '選擇能力'}</small></button>`;
  }
  function statBar(value, max, kind, label) { const percentage = max > 0 ? Math.max(0, Math.min(100, value / max * 100)) : 0; return `<div class="stat-bar ${kind}"><span class="bar-name">${label}</span><span class="bar-track"><i style="width:${percentage}%"></i></span><span class="bar-value">${Math.ceil(value)} <em>/ ${Math.ceil(max)}</em></span></div>`; }
  function ring(progress, label = '', sublabel = '') { return `<svg class="progress-ring" viewBox="0 0 160 160" aria-hidden="true"><circle class="ring-outer" cx="80" cy="80" r="76"/><circle class="ring-track" cx="80" cy="80" r="68"/><circle class="ring-value" cx="80" cy="80" r="68" pathLength="100" stroke-dasharray="${progress} 100"/></svg>${label ? `<strong class="ring-label">${label}</strong><small>${sublabel}</small>` : ''}`; }
  function castBar(actor, battleTime, flash = '') {
    const cast = actor.cast, move = cast && D.moves[cast.moveId], percent = cast ? Math.min(100, (battleTime - cast.startedAt) / cast.duration * 100) : 0;
    return `<div class="cast-bar ${cast ? 'casting' : ''} ${move?.id === 'crush' ? 'danger' : ''} ${flash}"><div class="cast-meta"><span>${flash === 'interrupted' ? '中斷！' : move ? `${move.id === 'crush' ? '⚠ ' : ''}${move.name}` : '準備出手'}</span><strong>${cast ? `${Math.max(0, cast.endAt - battleTime).toFixed(1)}<small>s</small>` : '—'}</strong></div><div class="cast-rail"><i style="width:${percent}%;--cast-phase:-${battleTime % 1.5}s"><b></b></i></div><small>${move?.id === 'crush' ? '危險攻擊 · 可以中斷' : cast ? '凝聚力量中' : '選擇下一個招式'}</small></div>`;
  }
  function characterArt() {
    return `<svg class="character-art" viewBox="0 0 360 520" aria-label="披著旅行斗篷的冒險者" role="img"><defs><linearGradient id="cloak" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#5b7478"/><stop offset=".5" stop-color="#283d49"/><stop offset="1" stop-color="#12212a"/></linearGradient><linearGradient id="steel"><stop stop-color="#c1c4b5"/><stop offset=".48" stop-color="#687c80"/><stop offset=".5" stop-color="#d4d5bc"/><stop offset="1" stop-color="#59686b"/></linearGradient><radialGradient id="heroGlow"><stop stop-color="#af936247"/><stop offset="1" stop-color="#af936200"/></radialGradient></defs><ellipse cx="180" cy="464" rx="125" ry="25" fill="#040b1080"/><ellipse cx="180" cy="460" rx="143" ry="40" fill="none" stroke="#a18a4a4d"/><path d="M48 460h264M180 422v76" stroke="#a18a4a35"/><circle cx="180" cy="230" r="175" fill="url(#heroGlow)"/><circle cx="180" cy="230" r="145" fill="none" stroke="#baa47321"/><path d="m144 343-7 84-13 29 43 4 11-109m16-9 9 86 1 32 43-5-17-29-5-88" fill="#263235" stroke="#748079" stroke-width="2"/><path d="m136 428 28 5-3 28-39-3Zm71 4 25-5 16 30-43 5Z" fill="#292821" stroke="#817555"/><path d="M127 173 89 278 63 407l91-30 28 13 76 10-23-144-6-89-47-47Z" fill="url(#cloak)" stroke="#9a9e833f" stroke-width="2"/><path d="m126 182-37 166-17 45 74-39 14-161m54-17 27 209-47-34-1-161" fill="#172b37"/><path d="m123 221 42 20 52-13-5 117-57 14-24-15Z" fill="#514d3d" stroke="#9c92713b"/><path d="m138 252 53 7m-53 23 59 5m-60 21 56 1" stroke="#9b95704d"/><path d="m131 195 74 122 12-5-72-119Z" fill="#866d46" stroke="#ad966a"/><path d="m122 312 91 1 1 15-85-1Z" fill="#211f1a"/><rect x="165" y="311" width="23" height="18" rx="2" fill="#9f8551"/><rect x="170" y="315" width="13" height="10" fill="#2c3027"/><path d="m115 219-18 70-2 36 19 7 22-106" fill="#435c61" stroke="#8c9c91"/><path d="m217 216 18 43 15 36-16 12-30-68" fill="#42585f" stroke="#8b9987"/><path d="m96 322 16 1 4 17-9 10-13-8Zm139-21 14-9 11 15-10 17-12-4Z" fill="#baa07c"/><path d="m220 175-22-59-41-13-34 47 8 47 25 24 31-2Z" fill="#182832" stroke="#6b8385" stroke-width="2"/><path d="m145 144 46-4 12 35-12 27-31-4-12-23Z" fill="#a79575"/><path d="m124 167 15-47 29-26 36 11 21 62-27-23-35-1-19 27 10 32-31-15Z" fill="url(#cloak)" stroke="#b8b59a70" stroke-width="2"/><path d="m150 170 42 1-8 28-22-3Z" fill="#182630"/><path d="m162 159 7 1m10-1 7-1" stroke="#e4c58d" stroke-width="2"/><path d="m240 321 16-16 65 103-4 21-18-10Z" fill="url(#steel)" stroke="#a8b6b1"/><path d="m236 314 28-17m-16 13-14-22" stroke="#b6a067" stroke-width="7" stroke-linecap="round"/><path d="m103 346-1 40" stroke="#8b7948" stroke-width="2"/><path d="m93 369 19 0 5 34-29 0Z" fill="#897247" stroke="#d2b87b"/><path d="m96 375 12 0 2 21-16 0Z" fill="#e3bf72"/><circle cx="101" cy="386" r="42" fill="url(#heroGlow)"/><path d="m79 393 43-129m111 116-17-112" stroke="#8b9c8c55" stroke-dasharray="4 7"/></svg>`;
  }
  function cost(move) { return Object.entries(move.cost || {}).map(([k, v]) => `${v} ${k === 'mana' ? 'MP' : 'SP'}`).join(' · ') || '無消耗'; }
  function ultimateChargeSpeed(id) { const value=D.moves[id]?.ultimateChargeCost||100; return value<=75?'快':value<=110?'普通':value<=145?'慢':'很慢'; }
  function skillDetail(skill){return `<span class="eyebrow">${escape(skill.category)}</span><h3>${escape(skill.name)}</h3><p>${escape(skill.description)}</p><p>觸發：${escape(skill.triggerType)}。持續效果只刷新時間，較強者覆蓋較弱者，不會疊層。</p><p class="effect-note">名詞說明：讀條＝敵人準備招式的時間；中斷＝取消該次準備；Buff＝強化自己；Debuff＝削弱敵人；刷新＝重新計算持續時間；不疊加＝不會重複增加強度。</p>`;}
  function effects(move) { return move.effects.map(e => e.type === 'interrupt' ? '中斷：命中時取消敵方目前讀條' : e.type === 'restore' ? `恢復：回復 ${e.amount} ${e.resource === 'stamina' ? 'SP' : 'MP'}` : e.type==='status'?`${e.status.name}：持續 ${e.status.duration} 秒（刷新時間，不重複疊加）`:e.type==='heal'?`治療：回復最大 HP ${e.ratio*100}%`:e.type).join('；') || '直接傷害：不會中斷敵方讀條'; }
  function compactMoveDetail(move){return `<h3>${escape(move.subtitle||move.name)}</h3><p class="compact-values">預估傷害 ${move.estimatedDamage?.toFixed(1)||'0'} · ${cost(move)}<br>攻擊時間 ${move.attackTime} · 讀條 ${move.castTime?.toFixed(2)||'—'} 秒<br>${({physical:'物理',magic:'魔法',spell:'咒語'})[move.damageType]}／${move.elements?.map(e=>D.elements[e]).join('＋')||'無屬性'}</p><p>${effects(move)}</p><p>必殺能量需求：${move.ultimateChargeCost||100}</p>${move.modifications?.length?`<p>修正：${move.modifications.map(escape).join('、')}</p>`:''}`;}
  function moveDetail(move, level, agility, permanent = false) {
    return `<div class="detail-icon tone-${tone(move.id)}">${icon(move.icon || 'sword', 72)}</div><small class="eyebrow">${move.kind === 'ultimate' ? 'ULTIMATE ART' : move.damageType === 'magic' ? 'ARCANE ART' : 'MARTIAL ART'}</small><h3>${escape(move.name)}${permanent ? '' : ` <span>Lv.${level}</span>`}</h3>${permanent && move.kind !== 'ultimate' ? stars(level) + `<p class="muted">永久 Lv.${level} / 3</p>` : ''}<p>${escape(move.description || '以力量擊向敵人。')}<br>${({physical:'物理',magic:'魔法',spell:'咒語'})[move.damageType]}／${move.elements?.map(e=>D.elements[e]).join('＋')||'無屬性'}</p><div class="detail-values"><div><small>${move.estimatedDamage!=null?"預估傷害（未爆擊）":"傷害倍率"}</small><strong>${move.estimatedDamage!=null?move.estimatedDamage.toFixed(1):Math.round(move.multiplier*100)}<em>${move.estimatedDamage!=null?"":"%"}</em></strong></div><div><small>消耗</small><strong>${cost(move)}</strong></div><div><small>攻擊時間</small><strong>${move.attackTime}</strong></div><div><small>必殺能量需求</small><strong>${move.ultimateChargeCost||100}</strong></div></div><p class="effect-note">${effects(move)}</p>${move.modifications?.length?`<p class="effect-note">目前修正：${move.modifications.map(escape).join("、")}</p>`:""}`;
  }
  root.GameUI = { escape, tone, stars, icon, button, tabs, card, slot, statBar, ring, castBar, characterArt, cost, effects, moveDetail, skillDetail, compactMoveDetail, ultimateChargeSpeed };
})(globalThis);
