const test=require('node:test'),assert=require('node:assert/strict');
const D=require('./data'),P=require('./progression'),W=require('./world'),R=require('./world-rewards'),Debug=require('./world-debug');
const make=()=>P.createRun(P.freshProgress(),P.defaultBuild(),()=>.5);
const sources={moves:D.moves,talents:D.skills,books:D.books,equipment:D.equipment};
test('世界內容：五區十一城、指定等級、無 NPC、所有引用有效',()=>{
 assert.equal(D.world.regions.length,5);assert.equal(D.dungeons.filter(d=>!d.generatedMapDungeon).length,11);assert.equal(D.explorationObjects.length,0);assert.deepEqual(D.dungeons.filter(d=>!d.generatedMapDungeon).map(d=>d.level),[12,20,38,50,70,85,110,130,160,175,190]);assert.ok(D.mapData.every(m=>m.dungeonIds.length));
 for(const pool of Object.values(D.rewardPools))for(const e of pool.entries){assert.ok(e.weight>0);assert.ok(e.rewardIds.length);for(const id of e.rewardIds)assert.ok(sources[e.rewardType][id],`${pool.id} references ${id}`);}
 for(const e of D.enemySpawnData){const m=D.monsters[e.type];assert.ok(m);assert.ok(D.world.regions.some(r=>r.id===e.regionId));for(const id of m.moves)assert.ok(D.moves[id]);for(const id of m.skills)assert.ok(D.skills[id]);assert.ok(D.rewardPools[m.dropPool]);}
 for(const d of D.dungeons){assert.deepEqual(d.enemyWaves.map(w=>w.role),D.dungeonTemplates[d.dungeonType]);assert.equal(d.enemyWaves.at(-1).type,d.bossId);for(const wave of d.enemyWaves){const m=D.monsters[wave.type];for(const id of m.moves)assert.ok(D.moves[id]);for(const id of m.skills)assert.ok(D.skills[id]);}}
});
test('區域跨度與外圍到核心梯度；精英是少量高等級個體',()=>{let last=0;const run=make();for(const r of D.world.regions){assert.ok(r.min>last);last=r.max;assert.ok(P.regionLevel(r.x,r.y)>P.regionLevel(r.bounds[0]+10,r.bounds[1]+10));const enemies=run.world.enemies.filter(e=>e.regionId===r.id);assert.ok(enemies.filter(e=>e.elite).length<enemies.length/4);for(const e of enemies.filter(e=>e.elite))assert.equal(e.level,P.regionLevel(e.x,e.y)+8);}});
test('Lv.1 可進入所有區域和地下城、道路全程可步行',()=>{const run=make();for(const r of D.world.regions){Debug.teleport(run,r.id);assert.equal(run.level,1);assert.equal(D.regionById[D.maps[run.currentMapId].regionId].legacyRegionId,r.id);assert.equal(W.blocked(run.position.x,run.position.y),false);}for(const d of D.dungeons){Debug.enter(run,d.id);assert.equal(P.dungeonEncounter(run).type,d.enemyWaves[0].type);}for(const road of D.world.roads)for(let i=1;i<road.length;i++)for(let t=0;t<=1;t+=.02){const a=road[i-1],b=road[i];assert.equal(W.blocked(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t),false);}});
test('所有地下城多種權重組合、指定組合／池、抽樣不改永久收藏',()=>{for(const d of D.dungeons){const result=Debug.sample(d.id,1000,'','',W.seeded(741));assert.equal(Object.keys(result.combinations).length,4);for(const r of d.rewardCombinationRules){const roll=R.dungeon(d.id,W.seeded(1),{combination:r.id});assert.equal(roll.combination,r.id);assert.equal(roll.rewards.length,r.draws.length);for(const reward of roll.rewards)assert.ok(sources[reward.kind][reward.id]);}assert.ok(Object.keys(result.rewards).length>4);}assert.equal(Debug.sample(D.dungeons[0].id,10,'',D.dungeons[0].rareRewardPool).count,10);assert.throws(()=>Debug.sample('bad',3));assert.throws(()=>Debug.sample(D.dungeons[0].id,NaN));});
test('魔法書先決招式均能由正式池取得，敵人強度隨等級上升',()=>{const possible=new Set(D.startingMoves);for(const p of Object.values(D.rewardPools))for(const e of p.entries)if(e.rewardType==='moves')e.rewardIds.forEach(id=>possible.add(id));for(const b of Object.values(D.books))assert.ok(possible.has(b.requirement.moveId),b.name);const type=D.enemySpawnData[0].type;const a=P.enemyDefinition(type,1),b=P.enemyDefinition(type,100);assert.ok(b.stats.hp>a.stats.hp*4);assert.ok(b.stats.stamina>a.stats.stamina);});
test('存檔向後相容：既有解鎖、永久等級與通關次數保留',()=>{const p=P.freshProgress();p.skills=Object.keys(D.skills);p.moves.fire=3;p.moves.black_light=2;p.books=['blacklight_book'];p.dungeonCompletions={abandoned_mine:4};p.completions=9;const loaded=P.loadProgress({getItem:()=>JSON.stringify(p)});assert.equal(loaded.warning,null);assert.equal(loaded.progress.moves.black_light,2);assert.equal(loaded.progress.skills.length,Object.keys(D.skills).length);assert.equal(loaded.progress.dungeonCompletions.abandoned_mine,4);assert.equal(loaded.progress.completions,9);});
test('世界 Debug 等級驗證與敵人調整不修改資料模板',()=>{const r=make(),e=r.world.enemies[0],original=D.enemySpawnData[0].level;Debug.setLevel(r,150);assert.equal(r.level,150);Debug.enemyLevel(r,e.id,200);assert.equal(e.level,200);assert.equal(D.enemySpawnData[0].level,original);assert.throws(()=>Debug.setLevel(r,0));assert.throws(()=>Debug.enemyLevel(r,e.id,Infinity));});
for(const d of D.dungeons)test(`實際引擎完成 ${d.name} 全 ${d.enemyWaves.length} 場，獎勵只發一次`,()=>{
 const p=P.freshProgress(),r=P.createRun(p);r.level=d.level+30;r.allocated.hp=1000;r.allocated.stamina=500;Debug.enter(r,d.id);assert.throws(()=>P.dungeonReward(p,r));
 for(let i=0;i<d.enemyWaves.length;i++){r.dungeon.stage=i;const e=P.dungeonEncounter(r),b=P.battleFor(r,e,()=>.99);for(let ticks=0;ticks<8000&&b.phase==='fighting';ticks++){if(!b.player.cast)b.choose('quick');b.advance(.05);}assert.equal(b.phase,'victory');for(const k of ['hp','mana','stamina'])assert.ok(b.player[k]<=b.player.stats[k]);P.grantExp(r,e.level,e.type);}
 const rewards=P.dungeonReward(p,r,W.seeded(121));assert.ok(rewards.length>=2);for(const reward of rewards)assert.ok(sources[reward.kind][reward.id]);assert.equal(p.dungeonCompletions[d.id],1);assert.deepEqual(P.dungeonReward(p,r),[]);assert.equal(p.completions,1);
});
