/* World diagnostics and atlas. Reward previews never modify permanent progress. */
(function(root){
 const D=typeof module!=='undefined'?require('./data.js'):root.GameData;
 const R=typeof module!=='undefined'?require('./world-rewards.js'):root.WorldRewards;
 const valid=(value,min,max)=>{const n=Number(value);if(!Number.isInteger(n)||n<min||n>max)throw Error(`請輸入 ${min}～${max} 的整數`);return n;};
 function teleport(run,id){const r=D.world.regions.find(r=>r.id===id);if(!r)throw Error('區域不存在');const d=D.dungeons.find(d=>d.regionId===id);run.dungeon=null;const Maps=typeof module!=='undefined'?require('./world-maps.js'):root.WorldMaps;if(d?.mapId)Maps.enter(run,d.mapId);run.position={x:d.x,y:d.y+65};return r;}
 function setLevel(run,n){run.level=valid(n,1,300);run.exp=0;run.points=0;}
 function enemyLevel(run,id,n){const e=run.world.enemies.find(e=>e.id===id);if(!e)throw Error('敵人不存在');e.level=valid(n,1,999);return e;}
 function enter(run,id){if(!D.dungeons.some(d=>d.id===id))throw Error('地下城不存在');run.dungeon={id,stage:0};}
 function sample(id,count,combination='',poolId='',rng=Math.random){count=valid(count,1,10000);const summary={count,combinations:{},rewards:{}};for(let i=0;i<count;i++){const roll=poolId?{combination:'指定獎勵池',rewards:[R.pool(poolId,rng)]}:R.dungeon(id,rng,combination?{combination}:{});summary.combinations[roll.combination]=(summary.combinations[roll.combination]||0)+1;for(const r of roll.rewards){const key=r.kind+':'+r.id;summary.rewards[key]=(summary.rewards[key]||0)+1;}}return summary;}
 function form(run){const opt=(id,name)=>`<option value="${id}">${name}</option>`;return `<div class="eyebrow">WORLD DIAGNOSTICS</div><h2 id="modal-title">世界測試</h2><p>傳送與等級只修改本局；抽樣只預覽，不發放收藏。</p><div class="world-tools"><label>區域<select id="world-region">${D.world.regions.map(r=>opt(r.id,r.name)).join('')}</select></label><button data-action="world-enemies">查看區域敵人池</button><button data-action="world-teleport">傳送至區域入口</button><label>玩家等級<input id="world-level" type="number" min="1" max="300" value="${run.level}"></label><button data-action="world-level">套用玩家等級</button><label>敵人<select id="world-enemy">${run.world.enemies.map(e=>opt(e.id,D.monsters[e.type].name+' Lv.'+e.level+' · '+e.id)).join('')}</select></label><label>敵人等級<input id="world-enemy-level" type="number" min="1" max="999" value="10"></label><button data-action="world-enemy-level">套用敵人等級</button><label>地下城<select id="world-dungeon">${D.dungeons.map(d=>opt(d.id,d.name+' Lv.'+d.recommendedLevel)).join('')}</select></label><button data-action="world-enter">直接挑戰地下城</button><label>指定組合<select id="world-combination">${opt('','依權重抽取')}${D.dungeons[0].rewardCombinationRules.map(r=>opt(r.id,r.id)).join('')}</select></label><label>指定池（優先於組合）<select id="world-pool">${opt('','使用所選地下城的組合')}${Object.keys(D.rewardPools).map(id=>opt(id,id)).join('')}</select></label><label>抽樣次數<input id="world-samples" type="number" min="1" max="10000" value="100"></label><button data-action="world-sample">重複抽樣</button><button data-action="world-inspect">檢視獎勵池</button></div><pre id="world-output" aria-live="polite">選擇地下城後可檢視池內容或重複抽樣。</pre><div class="modal-footer"><button data-action="close">返回探索</button></div>`;}
 function atlas(run){return `<div class="eyebrow">WORLD ATLAS</div><h2 id="modal-title">世界地圖</h2><p>所有區域自由通行。推薦等級代表危險程度。</p><svg class="world-atlas" viewBox="0 0 7200 4200" role="img" aria-label="五區世界地圖">${D.world.regions.map(r=>`<g><rect x="${r.bounds[0]}" y="${r.bounds[1]}" width="${r.bounds[2]}" height="${r.bounds[3]}" fill="${r.color}" stroke="#bcaa78" stroke-width="12"/><text x="${r.x}" y="${r.y-200}" text-anchor="middle" fill="#fff" font-size="160">${r.name}</text><text x="${r.x}" y="${r.y}" text-anchor="middle" fill="#efdab0" font-size="140">Lv.${r.min}–${r.max}</text></g>`).join('')}${D.dungeons.map(d=>`<circle cx="${d.x}" cy="${d.y}" r="40" fill="#dbb4ff"/>`).join('')}<circle cx="${run.position.x}" cy="${run.position.y}" r="75" fill="#fff" stroke="#97eee6" stroke-width="30"/></svg><p>白點：目前位置 · 紫點：地下城</p>${D.world.regions.map(r=>`<div class="atlas-region"><h3>${r.name} <small>Lv.${r.min}–${r.max}</small></h3>${D.dungeons.filter(d=>d.regionId===r.id).map(d=>`<p>◇ ${d.name} · Lv.${d.recommendedLevel} · ${d.enemyWaves.length} 場</p>`).join('')}</div>`).join('')}<div class="modal-footer"><button data-action="close">返回探索</button></div>`;}
 function routeAtlas(run){return `<div class="eyebrow">WORLD ATLAS · THIS RUN</div><h2 id="modal-title">世界地圖</h2><p>選擇大區，再選擇實際地圖。所有大區都能從 Lv.1 起跑，推薦等級僅供參考。</p><div class="route-grid">${D.regionData.map(r=>`<button class="route-card ${D.maps[run.currentMapId]?.regionId===r.id?'current':''}" data-action="world-region" data-id="${r.id}" style="--route-color:${r.color}"><strong>${r.name}</strong><small>${r.themeTags.slice(0,3).join(' · ')}</small><span>${r.mapIds.length} 張地圖 · Lv.1 起</span></button>`).join('')}</div><div class="modal-footer"><button data-action="close">返回探索</button></div>`;}
 function regionMaps(run,id){const r=D.regionById[id];if(!r)return routeAtlas(run);return `<div class="eyebrow">WORLD ATLAS · ${r.name}</div><h2 id="modal-title">${r.name}</h2><p>${r.description}。選擇地圖後可查看敵人、地下城與獎勵傾向。</p><div class="route-list">${r.mapIds.map(mapId=>{const m=D.maps[mapId];return `<button class="route-card ${run.currentMapId===mapId?'current':''}" data-action="world-map-detail" data-id="${mapId}" style="--route-color:${m.color}"><strong>${m.name}${run.currentMapId===mapId?' · 目前位置':''}</strong><small>推薦 Lv.${m.recommendedLevelMin}～${m.recommendedLevelMax}</small><span>${m.gameplayTags.slice(0,3).join(' · ')}</span></button>`;}).join('')}</div><div class="modal-footer"><button data-action="world-map">返回七大區</button><button data-action="close">返回探索</button></div>`;}
 function mapDetail(run,id){const m=D.maps[id];if(!m)return routeAtlas(run);const dungeons=m.dungeonIds.map(key=>D.dungeons.find(d=>d.id===key)).filter(Boolean);return `<div class="eyebrow">MAP ROUTE · ${D.regionById[m.regionId].name}</div><h2 id="modal-title">${m.name}</h2><p>${m.description}</p><div class="route-detail"><p><b>推薦等級</b> Lv.${m.recommendedLevelMin}～${m.recommendedLevelMax} · 危險度 ${m.dangerTier}/5</p><p><b>敵人特色</b> ${m.gameplayTags.join(' · ')}</p><p><b>主要元素</b> ${m.elementTendencies.join(' · ')}</p><p><b>可能地下城</b> ${dungeons.length?dungeons.map(d=>d.name+' Lv.'+d.recommendedLevel).join('、'):'目前未配置'}</p><p><b>獎勵傾向</b> ${D.regionById[m.regionId].rewardTendencies.join(' · ')}</p><p class="route-danger">可越級進入；若與推薦等級落差大，敵人可能難以擊敗。</p></div><div class="modal-footer"><button data-action="world-region" data-id="${m.regionId}">返回地圖列表</button><button data-action="world-enter-map" data-id="${id}">${run.currentMapId===id?'返回目前地圖':'前往這張地圖'}</button></div>`;}
 const api={teleport,setLevel,enemyLevel,enter,sample,form,atlas:routeAtlas,regionMaps,mapDetail};if(typeof module!=='undefined')module.exports=api;else root.WorldDebug=api;
})(globalThis);
